-- RUN THIS SCRIPT USING USER "ADIT_APP"

CREATE OR REPLACE SYNONYM &&ADIT_APP..USER_CONTACT FOR &&ADIT_SCHEMA..USER_CONTACT;
CREATE OR REPLACE SYNONYM &&ADIT_APP..USER_CONTACT_ID_SEQ FOR &&ADIT_SCHEMA..USER_CONTACT_ID_SEQ;