INSERT INTO &&ADIT_SCHEMA..MAINTENANCE_JOB(ID, NAME, IS_RUNNING) VALUES(1, 'Send documents to DVK', 0);
INSERT INTO &&ADIT_SCHEMA..MAINTENANCE_JOB(ID, NAME, IS_RUNNING) VALUES(2, 'Receive documents from DVK', 0);
INSERT INTO &&ADIT_SCHEMA..MAINTENANCE_JOB(ID, NAME, IS_RUNNING) VALUES(3, 'Update document status from DVK', 0);
INSERT INTO &&ADIT_SCHEMA..MAINTENANCE_JOB(ID, NAME, IS_RUNNING) VALUES(4, 'Update document status to DVK', 0);
INSERT INTO &&ADIT_SCHEMA..MAINTENANCE_JOB(ID, NAME, IS_RUNNING) VALUES(5, 'Delete documents from DVK', 0);
INSERT INTO &&ADIT_SCHEMA..MAINTENANCE_JOB(ID, NAME, IS_RUNNING) VALUES(6, 'Synchronize users with DVK', 0);
INSERT INTO &&ADIT_SCHEMA..MAINTENANCE_JOB(ID, NAME, IS_RUNNING) VALUES(7, 'Send notifications', 0);
INSERT INTO &&ADIT_SCHEMA..MAINTENANCE_JOB(ID, NAME, IS_RUNNING) VALUES(8, 'Clean temporary files', 0);
