//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.18 at 12:24:15 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.riik.ee/adit/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ee.adit.pojo;
