//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.09 at 04:42:08 PM EEST 
//

package ee.adit.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for GetDocumentListRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GetDocumentListRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="folder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="document_types" type="{http://producers.ametlikud-dokumendid.xtee.riik.ee/producer/ametlikud-dokumendid}ArrayOfDocumentType"/>
 *         &lt;element name="file_types" type="{http://producers.ametlikud-dokumendid.xtee.riik.ee/producer/ametlikud-dokumendid}ArrayOfFileType"/>
 *         &lt;element name="document_dvk_statuses" type="{http://producers.ametlikud-dokumendid.xtee.riik.ee/producer/ametlikud-dokumendid}ArrayOfDocumentDvkStatus"/>
 *         &lt;element name="document_workflow_statuses" type="{http://producers.ametlikud-dokumendid.xtee.riik.ee/producer/ametlikud-dokumendid}ArrayOfDocumentWorkflowStatus"/>
 *         &lt;element name="has_been_viewed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="is_deflated" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="creator_applications" type="{http://producers.ametlikud-dokumendid.xtee.riik.ee/producer/ametlikud-dokumendid}ArrayOfCreatorApplication"/>
 *         &lt;element name="search_phrase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="period_start" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="period_end" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="max_results" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="start_index" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="sort_by" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sort_order" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetDocumentListRequest", propOrder = {"folder", "documentTypes", "fileTypes", "documentDvkStatuses",
        "documentWorkflowStatuses", "hasBeenViewed", "isDeflated", "creatorApplications", "searchPhrase",
        "periodStart", "periodEnd", "maxResults", "startIndex", "sortBy", "sortOrder" })
public class GetDocumentListRequest {

    @XmlElement(required = true)
    private String folder;
    @XmlElement(name = "document_types", required = true)
    private ArrayOfDocumentType documentTypes;
    @XmlElement(name = "file_types")
    private ArrayOfFileType fileTypes;
    @XmlElement(name = "document_dvk_statuses", required = true)
    private ArrayOfDocumentDvkStatus documentDvkStatuses;
    @XmlElement(name = "document_workflow_statuses", required = true)
    private ArrayOfDocumentWorkflowStatus documentWorkflowStatuses;
    @XmlElement(name = "has_been_viewed")
    private Boolean hasBeenViewed;
    @XmlElement(name = "is_deflated")
    private Boolean isDeflated;
    @XmlElement(name = "creator_applications", required = true)
    private ArrayOfCreatorApplication creatorApplications;
    @XmlElement(name = "search_phrase", required = true)
    private String searchPhrase;
    @XmlElement(name = "period_start")
    private org.exolab.castor.types.Date periodStart;
    @XmlElement(name = "period_end")
    private org.exolab.castor.types.Date periodEnd;
    @XmlElement(name = "max_results", required = true)
    private Long maxResults;
    @XmlElement(name = "start_index", required = true)
    private Long startIndex;
    @XmlElement(name = "sort_by")
    private String sortBy;
    @XmlElement(name = "sort_order")
    private String sortOrder;
    

    /**
     * Gets the value of the folder property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFolder() {
        return folder;
    }

    /**
     * Sets the value of the folder property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setFolder(String value) {
        this.folder = value;
    }

    /**
     * Gets the value of the documentTypes property.
     * 
     * @return possible object is {@link ArrayOfDocumentType }
     * 
     */
    public ArrayOfDocumentType getDocumentTypes() {
        return documentTypes;
    }

    /**
     * Sets the value of the documentTypes property.
     * 
     * @param value
     *            allowed object is {@link ArrayOfDocumentType }
     * 
     */
    public void setDocumentTypes(ArrayOfDocumentType value) {
        this.documentTypes = value;
    }
    
    /**
     * Gets the value of the fileTypes property.
     * 
     * @return possible object is {@link ArrayOfFileType }
     * 
     */
    public ArrayOfFileType getFileTypes() {
        return fileTypes;
    }

    /**
     * Sets the value of the fileTypes property.
     * 
     * @param value
     *            allowed object is {@link ArrayOfFileType }
     * 
     */
    public void setFileTypes(ArrayOfFileType value) {
        this.fileTypes = value;
    }

    /**
     * Gets the value of the documentDvkStatuses property.
     * 
     * @return possible object is {@link ArrayOfDocumentDvkStatus }
     * 
     */
    public ArrayOfDocumentDvkStatus getDocumentDvkStatuses() {
        return documentDvkStatuses;
    }

    /**
     * Sets the value of the documentDvkStatuses property.
     * 
     * @param value
     *            allowed object is {@link ArrayOfDocumentDvkStatus }
     * 
     */
    public void setDocumentDvkStatuses(ArrayOfDocumentDvkStatus value) {
        this.documentDvkStatuses = value;
    }

    /**
     * Gets the value of the documentWorkflowStatuses property.
     * 
     * @return possible object is {@link ArrayOfDocumentWorkflowStatus }
     * 
     */
    public ArrayOfDocumentWorkflowStatus getDocumentWorkflowStatuses() {
        return documentWorkflowStatuses;
    }

    /**
     * Sets the value of the documentWorkflowStatuses property.
     * 
     * @param value
     *            allowed object is {@link ArrayOfDocumentWorkflowStatus }
     * 
     */
    public void setDocumentWorkflowStatuses(ArrayOfDocumentWorkflowStatus value) {
        this.documentWorkflowStatuses = value;
    }

    /**
     * Gets the value of the hasBeenViewed property.
     * 
     */
    public Boolean isHasBeenViewed() {
        return hasBeenViewed;
    }

    /**
     * Sets the value of the hasBeenViewed property.
     * 
     */
    public void setHasBeenViewed(Boolean value) {
        this.hasBeenViewed = value;
    }

    /**
     * Gets the value of the isDeflated property.
     * 
     */
    public Boolean isIsDeflated() {
        return isDeflated;
    }

    /**
     * Sets the value of the isDeflated property.
     * 
     */
    public void setIsDeflated(Boolean value) {
        this.isDeflated = value;
    }

    /**
     * Gets the value of the creatorApplications property.
     * 
     * @return possible object is {@link ArrayOfCreatorApplication }
     * 
     */
    public ArrayOfCreatorApplication getCreatorApplications() {
        return creatorApplications;
    }

    /**
     * Sets the value of the creatorApplications property.
     * 
     * @param value
     *            allowed object is {@link ArrayOfCreatorApplication }
     * 
     */
    public void setCreatorApplications(ArrayOfCreatorApplication value) {
        this.creatorApplications = value;
    }

    /**
     * Gets the value of the searchPhrase property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSearchPhrase() {
        return searchPhrase;
    }

    /**
     * Sets the value of the searchPhrase property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSearchPhrase(String value) {
        this.searchPhrase = value;
    }

    /**
     * Gets the value of the periodStart property.
     * 
     * @return possible object is {@link org.exolab.castor.types.Date }
     * 
     */
    public org.exolab.castor.types.Date getPeriodStart() {
		return periodStart;
	}

    /**
     * Sets the value of the periodStart property.
     * 
     * @param value
     *            allowed object is {@link org.exolab.castor.types.Date }
     * 
     */
    public void setPeriodStart(org.exolab.castor.types.Date periodStart) {
		this.periodStart = periodStart;
	}

    /**
     * Gets the value of the periodEnd property.
     * 
     * @return possible object is {@link org.exolab.castor.types.Date }
     * 
     */
	public org.exolab.castor.types.Date getPeriodEnd() {
		return periodEnd;
	}

    /**
     * Sets the value of the periodEnd property.
     * 
     * @param value
     *            allowed object is {@link org.exolab.castor.types.Date }
     * 
     */
	public void setPeriodEnd(org.exolab.castor.types.Date periodEnd) {
		this.periodEnd = periodEnd;
	}

	/**
     * Gets the value of the maxResults property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getMaxResults() {
        return maxResults;
    }

    /**
     * Sets the value of the maxResults property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setMaxResults(Long value) {
        this.maxResults = value;
    }

    /**
     * Gets the value of the startIndex property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getStartIndex() {
        return startIndex;
    }

    /**
     * Sets the value of the startIndex property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setStartIndex(Long value) {
        this.startIndex = value;
    }

    /**
     * Gets the value of the sortBy property.
     * 
     * @return possible object is {@link String }
     * 
     */
	public String getSortBy() {
		return sortBy;
	}

    /**
     * Sets the value of the sortBy property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
	public void setSortBy(String sortBy) {
		this.sortBy = sortBy;
	}

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return possible object is {@link String }
     * 
     */
	public String getSortOrder() {
		return sortOrder;
	}

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
	public void setSortOrder(String sortOrder) {
		this.sortOrder = sortOrder;
	}

}
