//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.08 at 04:45:18 PM EEST 
//

package ee.adit.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ModifyStatusRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ModifyStatusRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="document_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="document_status_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModifyStatusRequest", propOrder = {"documentId", "documentStatusId" })
public class ModifyStatusRequest {

    @XmlElement(name = "document_id", required = true)
    protected Long documentId;
    @XmlElement(name = "document_status_id", required = true)
    protected Long documentStatusId;

    /**
     * Gets the value of the documentId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the documentId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setDocumentId(Long value) {
        this.documentId = value;
    }

    /**
     * Gets the value of the documentStatusId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getDocumentStatusId() {
        return documentStatusId;
    }

    /**
     * Sets the value of the documentStatusId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setDocumentStatusId(Long value) {
        this.documentStatusId = value;
    }

}
