//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.07.13 at 04:42:34 PM EEST
//

package ee.adit.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PrepareSignatureResponse complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="PrepareSignatureResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="messages" type="{http://producers.ametlikud-dokumendid.xtee.riik.ee/producer/ametlikud-dokumendid}ArrayOfMessage"/>
 *         &lt;element name="signature_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="signature_hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="data_file_hashes" type="{http://producers.ametlikud-dokumendid.xtee.riik.ee/producer/ametlikud-dokumendid}ArrayOfDataFileHash"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrepareSignatureResponse", propOrder = {"success", "messages",
	"signatureId", "signatureHash", "dataFileHashes" })
public class PrepareSignatureResponse {
	@XmlElement(required = true)
    private boolean success;
    @XmlElement(required = true)
    private ArrayOfMessage messages;
    @XmlElement(name = "signature_id", required = true)
    private String signatureId;
    @XmlElement(name = "signature_hash", required = true)
    private String signatureHash;
    @XmlElement(name = "data_file_hashes")
    private ArrayOfDataFileHash dataFileHashes;

    /**
     * Gets the value of the success property.
     *
     */
    public boolean isSuccess() {
        return success;
    }

    /**
     * Sets the value of the success property.
     *
     */
    public void setSuccess(boolean value) {
        this.success = value;
    }

    /**
     * Gets the value of the messages property.
     *
     * @return possible object is {@link ArrayOfMessage }
     *
     */
    public ArrayOfMessage getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     *
     * @param value
     *            allowed object is {@link ArrayOfMessage }
     *
     */
    public void setMessages(ArrayOfMessage value) {
        this.messages = value;
    }

    /**
     * Gets the value of the signatureId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSignatureId() {
        return signatureId;
    }

    /**
     * Sets the value of the signatureId property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setSignatureId(String value) {
        this.signatureId = value;
    }

    /**
     * Gets the value of the signatureHash property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSignatureHash() {
        return signatureHash;
    }

    /**
     * Sets the value of the signatureHash property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setSignatureHash(String value) {
        this.signatureHash = value;
    }

    /**
     * Gets the value of the dataFileHashes property.
     *
     * @return possible object is {@link ArrayOfDataFileHash}
     *
     */
    public ArrayOfDataFileHash getDataFileHashes() {
        return dataFileHashes;
    }

    /**
     * Sets the value of the dataFileHashes property.
     *
     * @param value
     *            allowed object is {@link ArrayOfDataFileHash}
     *
     */
    public void setDataFileHashes(ArrayOfDataFileHash value) {
        this.dataFileHashes = value;
    }
}
