//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.13 at 04:42:34 PM EEST 
//

package ee.adit.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PrepareSignatureRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="PrepareSignatureRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="document_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="manifest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrepareSignatureRequest", propOrder = {"documentId", "manifest", "country", "state", "city", "zip",
        "signerCertificate" })
public class PrepareSignatureRequest {

    @XmlElement(name = "document_id", required = true)
    protected Long documentId;
    @XmlElement(required = true)
    protected String manifest;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(required = true)
    protected String city;
    @XmlElement(required = true)
    protected String zip;
    @XmlElement(required = true)
    protected PrepareSignatureRequestCert signerCertificate;

    /**
     * Gets the value of the documentId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the documentId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setDocumentId(Long value) {
        this.documentId = value;
    }

    /**
     * Gets the value of the manifest property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getManifest() {
        return manifest;
    }

    /**
     * Sets the value of the manifest property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setManifest(String value) {
        this.manifest = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setZip(String value) {
        this.zip = value;
    }

    /**
     * Gets the value of the signerCertificate property.
     * 
     * @return possible object is {@link PrepareSignatureRequestCert }
     * 
     */
    public PrepareSignatureRequestCert getSignerCertificate() {
        return signerCertificate;
    }

    /**
     * Sets the value of the signerCertificate property.
     * 
     * @param signerCertificate
     *            allowed object is {@link PrepareSignatureRequestCert }
     * 
     */
    public void setSignerCertificate(PrepareSignatureRequestCert signerCertificate) {
        this.signerCertificate = signerCertificate;
    }
}
