package ee.adit.dao.pojo;

// Generated 21.06.2010 14:02:03 by Hibernate Tools 3.2.4.GA

/**
 * Signature generated by hbm2java
 */
public class Signature implements java.io.Serializable {

    private static final long serialVersionUID = -8865939367303169765L;
    private long id;
    private Document document;
    private String userCode;
    private String signerRole;
    private String resolution;
    private String country;
    private String county;
    private String city;
    private String postIndex;
    private String signerCode;
    private String signerName;

    public Signature() {
    }

    public Signature(long id, Document document) {
        this.id = id;
        this.document = document;
    }

    public Signature(long id, Document document, String userCode, String signerRole, String resolution, String country,
            String county, String city, String postIndex, String signerCode, String signerName) {
        this.id = id;
        this.document = document;
        this.userCode = userCode;
        this.signerRole = signerRole;
        this.resolution = resolution;
        this.country = country;
        this.county = county;
        this.city = city;
        this.postIndex = postIndex;
        this.signerCode = signerCode;
        this.signerName = signerName;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Document getDocument() {
        return this.document;
    }

    public void setDocument(Document document) {
        this.document = document;
    }

    public String getUserCode() {
        return this.userCode;
    }

    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    public String getSignerRole() {
        return this.signerRole;
    }

    public void setSignerRole(String signerRole) {
        this.signerRole = signerRole;
    }

    public String getResolution() {
        return this.resolution;
    }

    public void setResolution(String resolution) {
        this.resolution = resolution;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getCounty() {
        return this.county;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPostIndex() {
        return this.postIndex;
    }

    public void setPostIndex(String postIndex) {
        this.postIndex = postIndex;
    }

    public String getSignerCode() {
        return signerCode;
    }

    public void setSignerCode(String signerCode) {
        this.signerCode = signerCode;
    }

    public String getSignerName() {
        return signerName;
    }

    public void setSignerName(String signerName) {
        this.signerName = signerName;
    }
}
