-- File types --

INSERT INTO &&ADIT_SCHEMA..DOCUMENT_FILE_TYPE(ID, DESCRIPTION) VALUES(1, 'Document file');
INSERT INTO &&ADIT_SCHEMA..DOCUMENT_FILE_TYPE(ID, DESCRIPTION) VALUES(2, 'Signature container');
INSERT INTO &&ADIT_SCHEMA..DOCUMENT_FILE_TYPE(ID, DESCRIPTION) VALUES(3, 'Signature container draft');
INSERT INTO &&ADIT_SCHEMA..DOCUMENT_FILE_TYPE(ID, DESCRIPTION) VALUES(4, 'ZIP Archive');