package ee.adit.dvk.api.ml;

import java.lang.reflect.Field;
import java.math.BigDecimal;

// Generated 7.02.2010 22:22:31 by Hibernate Tools 3.2.4.GA

import ee.adit.dvk.api.DVKAPI.DvkType;
import ee.adit.dvk.api.ISettingObserver;

/**
 * DhlSettings generated by hbm2java
 */
public class PojoSettings implements ISettingObserver, java.io.Serializable {
    public static class FieldNames {
        public static final String id = "id";
        public static final String institutionCode = "institutionCode";
        public static final String institutionName = "institutionName";
        public static final String personalIdCode = "personalIdCode";
        public static final String unitId = "unitId";
        public static final String subdivisionCode = "subdivisionCode";
        public static final String occupationCode = "occupationCode";
        public static final String PojoName = "PojoName";
    }

    /**
     *
     */
    private static final long serialVersionUID = -8117705617354641084L;
    protected long id;
    protected String institutionCode;
    protected String institutionName;
    protected String personalIdCode;
    protected long unitId;
    protected BigDecimal subdivisionCode;
    protected BigDecimal occupationCode;
    final static String PojoName = PojoSettings.class.getName();

    public PojoSettings() {
    }

    public PojoSettings(long id) {
        this.id = id;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getInstitutionCode() {
        return this.institutionCode;
    }

    public void setInstitutionCode(String institutionCode) {
        this.institutionCode = institutionCode;
    }

    public String getInstitutionName() {
        return this.institutionName;
    }

    public void setInstitutionName(String institutionName) {
        this.institutionName = institutionName;
    }

    public String getPersonalIdCode() {
        return this.personalIdCode;
    }

    public void setPersonalIdCode(String personalIdCode) {
        this.personalIdCode = personalIdCode;
    }

    public long getUnitId() {
        return this.unitId;
    }

    public void setUnitId(long unitId) {
        this.unitId = unitId;
    }

    public BigDecimal getSubdivisionCode() {
        return this.subdivisionCode;
    }

    public void setSubdivisionCode(BigDecimal subdivisionCode) {
        this.subdivisionCode = subdivisionCode;
    }

    public BigDecimal getOccupationCode() {
        return this.occupationCode;
    }

    public void setOccupationCode(BigDecimal occupationCode) {
        this.occupationCode = occupationCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }

        if (obj == null || !(obj instanceof PojoSettings)) {
            return false;
        }

        PojoSettings other = (PojoSettings) obj;

        return id == other.id;
    }

    @Override
    public String toString() {
        return Util.getDump(this);
    }

    public void printOutFields() {
        Field[] fields = getClass().getDeclaredFields();
        for (Field f : fields) {
            System.out.println("public final String " + f.getName() + " = \"" + f.getName() + "\";");
        }
    }

    public DvkType getType() {
        return DvkType.Settings;
    }
}
