package ee.adit.dvk.api.ml;

import java.math.BigDecimal;

// Generated 4.02.2010 13:44:05 by Hibernate Tools 3.2.4.GA

import ee.adit.dvk.api.DVKAPI.DvkType;
import ee.adit.dvk.api.ICounterObserver;

/**
 * DhlCounter generated by hbm2java
 */
public class PojoCounter implements ICounterObserver, java.io.Serializable {
    public static class FieldNames {
        public static final String dhlId = "dhlId";
    }

    final static String PojoName = PojoCounter.class.getName();
    private static final long serialVersionUID = 7633241410878033884L;
    protected BigDecimal dhlId;

    public PojoCounter() {
    }

    public PojoCounter(BigDecimal dhlId) {
        this.dhlId = dhlId;
    }

    public BigDecimal getDhlId() {
        return this.dhlId;
    }

    public void setDhlId(BigDecimal dhlId) {
        this.dhlId = dhlId;
    }

    @Override
    public PojoCounter clone() {
        return new PojoCounter(dhlId);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }

        if (obj == null || !(obj instanceof PojoCounter)) {
            return false;
        }

        PojoCounter other = (PojoCounter) obj;

        return Util.hasSameValue(dhlId, other.dhlId);
    }

    public DvkType getType() {
        return DvkType.Counter;
    }
}
