package ee.adit.dao.pojo;

// Generated 21.06.2010 11:12:30 by Hibernate Tools 3.2.4.GA

/**
 * AccessRestrictionId generated by hbm2java
 */
public class AccessRestrictionId implements java.io.Serializable {

	private String remoteApplication;
	private String userCode;

	public AccessRestrictionId() {
	}

	public AccessRestrictionId(String remoteApplication, String userCode) {
		this.remoteApplication = remoteApplication;
		this.userCode = userCode;
	}

	public String getRemoteApplication() {
		return this.remoteApplication;
	}

	public void setRemoteApplication(String remoteApplication) {
		this.remoteApplication = remoteApplication;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccessRestrictionId))
			return false;
		AccessRestrictionId castOther = (AccessRestrictionId) other;

		return ((this.getRemoteApplication() == castOther
				.getRemoteApplication()) || (this.getRemoteApplication() != null
				&& castOther.getRemoteApplication() != null && this
				.getRemoteApplication()
				.equals(castOther.getRemoteApplication())))
				&& ((this.getUserCode() == castOther.getUserCode()) || (this
						.getUserCode() != null
						&& castOther.getUserCode() != null && this
						.getUserCode().equals(castOther.getUserCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getRemoteApplication() == null ? 0 : this
						.getRemoteApplication().hashCode());
		result = 37 * result
				+ (getUserCode() == null ? 0 : this.getUserCode().hashCode());
		return result;
	}

}
