package ee.adit.dao.pojo;

// Generated 21.06.2010 12:03:01 by Hibernate Tools 3.2.4.GA

/**
 * AccessRestriction generated by hbm2java
 */
public class AccessRestriction implements java.io.Serializable {

	private long id;
	private AditUser aditUser;
	private RemoteApplication remoteApplication;
	private String restriction;

	public AccessRestriction() {
	}

	public AccessRestriction(long id, AditUser aditUser,
			RemoteApplication remoteApplication) {
		this.id = id;
		this.aditUser = aditUser;
		this.remoteApplication = remoteApplication;
	}

	public AccessRestriction(long id, AditUser aditUser,
			RemoteApplication remoteApplication, String restriction) {
		this.id = id;
		this.aditUser = aditUser;
		this.remoteApplication = remoteApplication;
		this.restriction = restriction;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public AditUser getAditUser() {
		return this.aditUser;
	}

	public void setAditUser(AditUser aditUser) {
		this.aditUser = aditUser;
	}

	public RemoteApplication getRemoteApplication() {
		return this.remoteApplication;
	}

	public void setRemoteApplication(RemoteApplication remoteApplication) {
		this.remoteApplication = remoteApplication;
	}

	public String getRestriction() {
		return this.restriction;
	}

	public void setRestriction(String restriction) {
		this.restriction = restriction;
	}

}
