package ee.adit.dao.pojo;
// Generated 2.06.2010 13:39:35 by Hibernate Tools 3.2.4.GA



/**
 * AccessRestriction generated by hbm2java
 */
public class AccessRestriction  implements java.io.Serializable {


     private AccessRestrictionId id;
     private String restriction;

    public AccessRestriction() {
    }

	
    public AccessRestriction(AccessRestrictionId id) {
        this.id = id;
    }
    public AccessRestriction(AccessRestrictionId id, String restriction) {
       this.id = id;
       this.restriction = restriction;
    }
   
    public AccessRestrictionId getId() {
        return this.id;
    }
    
    public void setId(AccessRestrictionId id) {
        this.id = id;
    }
    public String getRestriction() {
        return this.restriction;
    }
    
    public void setRestriction(String restriction) {
        this.restriction = restriction;
    }




}


