package ee.adit.dao.pojo;

// Generated 2.06.2010 13:39:35 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * AditLog generated by hbm2java
 */
public class AditLog implements java.io.Serializable {

	private long id;
	private String tableName;
	private String columnName;
	private String oldValue;
	private String newValue;
	private Date logDate;
	private String remoteApplicationShortName;
	private String xteeUserCode;
	private String xteeInstitutionCode;
	private String dbUser;

	public AditLog() {
	}

	public AditLog(long id) {
		this.id = id;
	}

	public AditLog(long id, String tableName, String columnName,
			String oldValue, String newValue, Date logDate,
			String remoteApplicationShortName, String xteeUserCode,
			String xteeInstitutionCode, String dbUser) {
		this.id = id;
		this.tableName = tableName;
		this.columnName = columnName;
		this.oldValue = oldValue;
		this.newValue = newValue;
		this.logDate = logDate;
		this.remoteApplicationShortName = remoteApplicationShortName;
		this.xteeUserCode = xteeUserCode;
		this.xteeInstitutionCode = xteeInstitutionCode;
		this.dbUser = dbUser;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}

	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	public String getRemoteApplicationShortName() {
		return this.remoteApplicationShortName;
	}

	public void setRemoteApplicationShortName(String remoteApplicationShortName) {
		this.remoteApplicationShortName = remoteApplicationShortName;
	}

	public String getXteeUserCode() {
		return this.xteeUserCode;
	}

	public void setXteeUserCode(String xteeUserCode) {
		this.xteeUserCode = xteeUserCode;
	}

	public String getXteeInstitutionCode() {
		return this.xteeInstitutionCode;
	}

	public void setXteeInstitutionCode(String xteeInstitutionCode) {
		this.xteeInstitutionCode = xteeInstitutionCode;
	}

	public String getDbUser() {
		return this.dbUser;
	}

	public void setDbUser(String dbUser) {
		this.dbUser = dbUser;
	}

}
