package ee.adit.dao.pojo;

// Generated 21.06.2010 14:02:03 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import ee.adit.service.DocumentService;
import ee.adit.util.CustomXTeeHeader;

/**
 * DocumentHistory generated by hbm2java
 */
public class DocumentHistory implements java.io.Serializable {

	private static final long serialVersionUID = 1886348010778047855L;
	private Long id;
	private String remoteApplicationName;
	private long documentId;
	private String documentHistoryType;
	private String description;
	private Date eventDate;
	private String userCode;
	private String userName;
	private String notificationStatus;
	private String xteeNotificationId;
	private String xteeUserCode;
	private String xteeUserName;

	public DocumentHistory() {
	}

	public DocumentHistory(Long id, long documentId) {
		this.id = id;
		this.documentId = documentId;
	}

	public DocumentHistory(Long id, String remoteApplicationName,
			long documentId, String documentHistoryType, String description,
			Date eventDate, String userCode, String userName, String notificationStatus,
			String xteeNotificationId, String xteeUserCode, String xteeUserName) {
		this.id = id;
		this.remoteApplicationName = remoteApplicationName;
		this.documentId = documentId;
		this.documentHistoryType = documentHistoryType;
		this.description = description;
		this.eventDate = eventDate;
		this.userCode = userCode;
		this.userName = userName;
		this.notificationStatus = notificationStatus;
		this.xteeNotificationId = xteeNotificationId;
		this.xteeUserCode = xteeUserCode;
		this.xteeUserName = xteeUserName;
	}
	
	public DocumentHistory(String historyType, Long documentId, Date eventDate,
			AditUser user, AditUser xroadUser, CustomXTeeHeader header) {
		this.setRemoteApplicationName(header.getInfosysteem());
		this.setDocumentId(documentId);
		this.setDocumentHistoryType(historyType);
		this.setEventDate(eventDate);
		this.setUserCode(user.getUserCode());
		this.setUserName(user.getFullName());
		this.setXteeUserCode(header.getIsikukood());
		if (xroadUser != null) {
			this.setXteeUserName(xroadUser.getFullName());
		}
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRemoteApplicationName() {
		return this.remoteApplicationName;
	}

	public void setRemoteApplicationName(String remoteApplicationName) {
		this.remoteApplicationName = remoteApplicationName;
	}

	public long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(long documentId) {
		this.documentId = documentId;
	}

	public String getDocumentHistoryType() {
		return this.documentHistoryType;
	}

	public void setDocumentHistoryType(String documentHistoryType) {
		this.documentHistoryType = documentHistoryType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}
	
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getNotificationStatus() {
		return this.notificationStatus;
	}

	public void setNotificationStatus(String notificationStatus) {
		this.notificationStatus = notificationStatus;
	}

	public String getXteeNotificationId() {
		return this.xteeNotificationId;
	}

	public void setXteeNotificationId(String xteeNotificationId) {
		this.xteeNotificationId = xteeNotificationId;
	}

	public String getXteeUserCode() {
		return this.xteeUserCode;
	}

	public void setXteeUserCode(String xteeUserCode) {
		this.xteeUserCode = xteeUserCode;
	}

	public String getXteeUserName() {
		return this.xteeUserName;
	}

	public void setXteeUserName(String xteeUserName) {
		this.xteeUserName = xteeUserName;
	}
}
