package ee.adit.dao.pojo;

// Generated 27.05.2010 12:13:12 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentDvkStatus generated by hbm2java
 */
public class DocumentDvkStatus implements java.io.Serializable {

	private long id;
	private String description;
	private Set documentSharings = new HashSet(0);
	private Set documents = new HashSet(0);

	public DocumentDvkStatus() {
	}

	public DocumentDvkStatus(long id) {
		this.id = id;
	}

	public DocumentDvkStatus(long id, String description, Set documentSharings,
			Set documents) {
		this.id = id;
		this.description = description;
		this.documentSharings = documentSharings;
		this.documents = documents;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDocumentSharings() {
		return this.documentSharings;
	}

	public void setDocumentSharings(Set documentSharings) {
		this.documentSharings = documentSharings;
	}

	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

}
