package ee.adit.dao.pojo;

// Generated 2.06.2010 13:39:35 by Hibernate Tools 3.2.4.GA

/**
 * DocumentHistoryType generated by hbm2java
 */
public class DocumentHistoryType implements java.io.Serializable {

	private long id;
	private String name;
	private String description;

	public DocumentHistoryType() {
	}

	public DocumentHistoryType(long id) {
		this.id = id;
	}

	public DocumentHistoryType(long id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
