package ee.adit.dao.pojo;

// Generated 2.06.2010 13:39:35 by Hibernate Tools 3.2.4.GA

/**
 * DocumentWfStatus generated by hbm2java
 */
public class DocumentWfStatus implements java.io.Serializable {

	private long id;
	private String description;
	private String name;

	public DocumentWfStatus() {
	}

	public DocumentWfStatus(long id) {
		this.id = id;
	}

	public DocumentWfStatus(long id, String description, String name) {
		this.id = id;
		this.description = description;
		this.name = name;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
