package ee.adit.dao.pojo;

// Generated 21.06.2010 12:26:14 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Document generated by hbm2java
 */
public class Document implements java.io.Serializable {

	private long id;
	private DocumentType documentType;
	private Document document;
	private String guid;
	private String title;
	private String creatorCode;
	private Date creationDate;
	private String remoteApplication;
	private Date lastModifiedDate;
	private Long documentDvkStatusId;
	private Long dvkId;
	private Long documentWfStatusId;
	private Boolean locked;
	private Date lockingDate;
	private Boolean signable;
	private Boolean deflated;
	private Date deflateDate;
	private Boolean deleted;
	private Set documents = new HashSet(0);
	private Set documentFiles = new HashSet(0);
	private Set signatures = new HashSet(0);
	private Set documentHistories = new HashSet(0);

	public Document() {
	}

	public Document(long id, DocumentType documentType, String creatorCode) {
		this.id = id;
		this.documentType = documentType;
		this.creatorCode = creatorCode;
	}

	public Document(long id, DocumentType documentType, Document document,
			String guid, String title, String creatorCode, Date creationDate,
			String remoteApplication, Date lastModifiedDate,
			Long documentDvkStatusId, Long dvkId, Long documentWfStatusId,
			Boolean locked, Date lockingDate, Boolean signable,
			Boolean deflated, Date deflateDate, Boolean deleted, Set documents,
			Set documentFiles, Set signatures, Set documentHistories) {
		this.id = id;
		this.documentType = documentType;
		this.document = document;
		this.guid = guid;
		this.title = title;
		this.creatorCode = creatorCode;
		this.creationDate = creationDate;
		this.remoteApplication = remoteApplication;
		this.lastModifiedDate = lastModifiedDate;
		this.documentDvkStatusId = documentDvkStatusId;
		this.dvkId = dvkId;
		this.documentWfStatusId = documentWfStatusId;
		this.locked = locked;
		this.lockingDate = lockingDate;
		this.signable = signable;
		this.deflated = deflated;
		this.deflateDate = deflateDate;
		this.deleted = deleted;
		this.documents = documents;
		this.documentFiles = documentFiles;
		this.signatures = signatures;
		this.documentHistories = documentHistories;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public DocumentType getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(DocumentType documentType) {
		this.documentType = documentType;
	}

	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCreatorCode() {
		return this.creatorCode;
	}

	public void setCreatorCode(String creatorCode) {
		this.creatorCode = creatorCode;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getRemoteApplication() {
		return this.remoteApplication;
	}

	public void setRemoteApplication(String remoteApplication) {
		this.remoteApplication = remoteApplication;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Long getDocumentDvkStatusId() {
		return this.documentDvkStatusId;
	}

	public void setDocumentDvkStatusId(Long documentDvkStatusId) {
		this.documentDvkStatusId = documentDvkStatusId;
	}

	public Long getDvkId() {
		return this.dvkId;
	}

	public void setDvkId(Long dvkId) {
		this.dvkId = dvkId;
	}

	public Long getDocumentWfStatusId() {
		return this.documentWfStatusId;
	}

	public void setDocumentWfStatusId(Long documentWfStatusId) {
		this.documentWfStatusId = documentWfStatusId;
	}

	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	public Date getLockingDate() {
		return this.lockingDate;
	}

	public void setLockingDate(Date lockingDate) {
		this.lockingDate = lockingDate;
	}

	public Boolean getSignable() {
		return this.signable;
	}

	public void setSignable(Boolean signable) {
		this.signable = signable;
	}

	public Boolean getDeflated() {
		return this.deflated;
	}

	public void setDeflated(Boolean deflated) {
		this.deflated = deflated;
	}

	public Date getDeflateDate() {
		return this.deflateDate;
	}

	public void setDeflateDate(Date deflateDate) {
		this.deflateDate = deflateDate;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

	public Set getDocumentFiles() {
		return this.documentFiles;
	}

	public void setDocumentFiles(Set documentFiles) {
		this.documentFiles = documentFiles;
	}

	public Set getSignatures() {
		return this.signatures;
	}

	public void setSignatures(Set signatures) {
		this.signatures = signatures;
	}

	public Set getDocumentHistories() {
		return this.documentHistories;
	}

	public void setDocumentHistories(Set documentHistories) {
		this.documentHistories = documentHistories;
	}

}
