package ee.adit.dao.pojo;

// Generated 27.05.2010 12:13:12 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * DocumentHistory generated by hbm2java
 */
public class DocumentHistory implements java.io.Serializable {

	private long id;
	private DocumentHistoryType documentHistoryType;
	private RemoteApplication remoteApplication;
	private Document document;
	private String description;
	private Date eventDate;
	private String userCode;
	private String notificationStatus;
	private String xteeNotificationId;

	public DocumentHistory() {
	}

	public DocumentHistory(long id, Document document) {
		this.id = id;
		this.document = document;
	}

	public DocumentHistory(long id, DocumentHistoryType documentHistoryType,
			RemoteApplication remoteApplication, Document document,
			String description, Date eventDate, String userCode,
			String notificationStatus, String xteeNotificationId) {
		this.id = id;
		this.documentHistoryType = documentHistoryType;
		this.remoteApplication = remoteApplication;
		this.document = document;
		this.description = description;
		this.eventDate = eventDate;
		this.userCode = userCode;
		this.notificationStatus = notificationStatus;
		this.xteeNotificationId = xteeNotificationId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public DocumentHistoryType getDocumentHistoryType() {
		return this.documentHistoryType;
	}

	public void setDocumentHistoryType(DocumentHistoryType documentHistoryType) {
		this.documentHistoryType = documentHistoryType;
	}

	public RemoteApplication getRemoteApplication() {
		return this.remoteApplication;
	}

	public void setRemoteApplication(RemoteApplication remoteApplication) {
		this.remoteApplication = remoteApplication;
	}

	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getNotificationStatus() {
		return this.notificationStatus;
	}

	public void setNotificationStatus(String notificationStatus) {
		this.notificationStatus = notificationStatus;
	}

	public String getXteeNotificationId() {
		return this.xteeNotificationId;
	}

	public void setXteeNotificationId(String xteeNotificationId) {
		this.xteeNotificationId = xteeNotificationId;
	}

}
