package ee.adit.dao.pojo;

// Generated 2.06.2010 13:39:35 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Document generated by hbm2java
 */
public class Document implements java.io.Serializable {

	private long id;
	private String guid;
	private String title;
	private String type;
	private String creatorCode;
	private Date creationDate;
	private String remoteApplicationShortName;
	private Date lastModifiedDate;
	private Long documentDvkStatusId;
	private Long dvkId;
	private Long documentWfStatusId;
	private Long parentId;
	private Boolean locked;
	private Date lockingDate;
	private Boolean signable;
	private Boolean deflated;
	private Date deflateDate;
	private Boolean deleted;
	private Set signatures = new HashSet(0);

	public Document() {
	}

	public Document(long id, String type, String creatorCode) {
		this.id = id;
		this.type = type;
		this.creatorCode = creatorCode;
	}

	public Document(long id, String guid, String title, String type,
			String creatorCode, Date creationDate,
			String remoteApplicationShortName, Date lastModifiedDate,
			Long documentDvkStatusId, Long dvkId, Long documentWfStatusId,
			Long parentId, Boolean locked, Date lockingDate, Boolean signable,
			Boolean deflated, Date deflateDate, Boolean deleted, Set signatures) {
		this.id = id;
		this.guid = guid;
		this.title = title;
		this.type = type;
		this.creatorCode = creatorCode;
		this.creationDate = creationDate;
		this.remoteApplicationShortName = remoteApplicationShortName;
		this.lastModifiedDate = lastModifiedDate;
		this.documentDvkStatusId = documentDvkStatusId;
		this.dvkId = dvkId;
		this.documentWfStatusId = documentWfStatusId;
		this.parentId = parentId;
		this.locked = locked;
		this.lockingDate = lockingDate;
		this.signable = signable;
		this.deflated = deflated;
		this.deflateDate = deflateDate;
		this.deleted = deleted;
		this.signatures = signatures;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getCreatorCode() {
		return this.creatorCode;
	}

	public void setCreatorCode(String creatorCode) {
		this.creatorCode = creatorCode;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getRemoteApplicationShortName() {
		return this.remoteApplicationShortName;
	}

	public void setRemoteApplicationShortName(String remoteApplicationShortName) {
		this.remoteApplicationShortName = remoteApplicationShortName;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Long getDocumentDvkStatusId() {
		return this.documentDvkStatusId;
	}

	public void setDocumentDvkStatusId(Long documentDvkStatusId) {
		this.documentDvkStatusId = documentDvkStatusId;
	}

	public Long getDvkId() {
		return this.dvkId;
	}

	public void setDvkId(Long dvkId) {
		this.dvkId = dvkId;
	}

	public Long getDocumentWfStatusId() {
		return this.documentWfStatusId;
	}

	public void setDocumentWfStatusId(Long documentWfStatusId) {
		this.documentWfStatusId = documentWfStatusId;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	public Date getLockingDate() {
		return this.lockingDate;
	}

	public void setLockingDate(Date lockingDate) {
		this.lockingDate = lockingDate;
	}

	public Boolean getSignable() {
		return this.signable;
	}

	public void setSignable(Boolean signable) {
		this.signable = signable;
	}

	public Boolean getDeflated() {
		return this.deflated;
	}

	public void setDeflated(Boolean deflated) {
		this.deflated = deflated;
	}

	public Date getDeflateDate() {
		return this.deflateDate;
	}

	public void setDeflateDate(Date deflateDate) {
		this.deflateDate = deflateDate;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Set getSignatures() {
		return this.signatures;
	}

	public void setSignatures(Set signatures) {
		this.signatures = signatures;
	}

}
