package ee.adit.dao.pojo;

// Generated 2.06.2010 13:39:35 by Hibernate Tools 3.2.4.GA

/**
 * NotificationType generated by hbm2java
 */
public class NotificationType implements java.io.Serializable {

	private String shortName;
	private String description;

	public NotificationType() {
	}

	public NotificationType(String shortName) {
		this.shortName = shortName;
	}

	public NotificationType(String shortName, String description) {
		this.shortName = shortName;
		this.description = description;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
