//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.02 at 02:26:06 PM EEST 
//

package ee.adit.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for GetDocumentFileRequest complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="GetDocumentFileRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="document_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="file_id_list" type="{http://producers.ametlikud-dokumendid.xtee.riik.ee/producer/ametlikud-dokumendid}ArrayOfFileId"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetDocumentFileRequest", propOrder = {"documentId", "fileIdList" })
public class GetDocumentFileRequest {

    @XmlElement(name = "document_id", required = true)
    private Long documentId;
    @XmlElement(name = "file_id_list", required = true)
    private ArrayOfFileId fileIdList;

    /**
     * Gets the value of the documentId property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the documentId property.
     * 
     * @param value
     *            allowed object is {@link Long }
     * 
     */
    public void setDocumentId(Long value) {
        this.documentId = value;
    }

    /**
     * Gets the value of the fileIdList property.
     * 
     * @return possible object is {@link ArrayOfFileId }
     * 
     */
    public ArrayOfFileId getFileIdList() {
        return fileIdList;
    }

    /**
     * Sets the value of the fileIdList property.
     * 
     * @param value
     *            allowed object is {@link ArrayOfFileId }
     * 
     */
    public void setFileIdList(ArrayOfFileId value) {
        this.fileIdList = value;
    }

}
