package ee.adit.test.util;

import org.bouncycastle.cert.ocsp.CertificateID;

import eu.europa.esig.dss.DSSRevocationUtils;
import eu.europa.esig.dss.x509.CertificateToken;
import junit.framework.TestCase;

/**
 * The class <code>DependencyLoadedTest</code> contains tests for the class
 * {@link DSSRevocationUtils}.
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 31.03.11 17:36
 *
 * @author Jaak Lember, Interinx, jaak@interinx.com
 */
public class DependencyLoadedTest extends TestCase {

	/**
	 * Construct new test instance.
	 *
	 * @param name the test name
	 */
	public DependencyLoadedTest(String name) {
		super(name);
	}

	/**
	 * Run test
	 */
	public void testDependencyExists() {
		try {
			CertificateID cid = DSSRevocationUtils.getOCSPCertificateID(
					new CertificateToken(null), null);
		} catch (NullPointerException npe) {
			// npe.printStackTrace();
			assertEquals("X509 certificate is missing", npe.getMessage());
		}
	}

}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames =
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = getFileExtension(QString;)
 * package = ee.adit.test.util
 * package.sourceFolder = adit-war/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = DependencyLoadedTest
 * testClassType = eu.europa.esig.dss.DSSRevocationUtils
 */