package ee.adit.dao;

// Generated 21.05.2010 14:11:24 by Hibernate Tools 3.2.4.GA

/**
 * AccessRestriction generated by hbm2java
 */
public class AccessRestriction implements java.io.Serializable {

	private AccessRestrictionId id;

	public AccessRestriction() {
	}

	public AccessRestriction(AccessRestrictionId id) {
		this.id = id;
	}

	public AccessRestrictionId getId() {
		return this.id;
	}

	public void setId(AccessRestrictionId id) {
		this.id = id;
	}

}
