package ee.adit.dao;

// Generated 21.05.2010 16:49:43 by Hibernate Tools 3.2.4.GA

/**
 * AccessRestriction generated by hbm2java
 */
public class AccessRestriction implements java.io.Serializable {

	private AccessRestrictionId id;
	private RemoteApplication remoteApplication;

	public AccessRestriction() {
	}

	public AccessRestriction(AccessRestrictionId id,
			RemoteApplication remoteApplication) {
		this.id = id;
		this.remoteApplication = remoteApplication;
	}

	public AccessRestrictionId getId() {
		return this.id;
	}

	public void setId(AccessRestrictionId id) {
		this.id = id;
	}

	public RemoteApplication getRemoteApplication() {
		return this.remoteApplication;
	}

	public void setRemoteApplication(RemoteApplication remoteApplication) {
		this.remoteApplication = remoteApplication;
	}

}
