package ee.adit.dao;

// Generated 21.05.2010 16:49:43 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentWfStatus generated by hbm2java
 */
public class DocumentWfStatus implements java.io.Serializable {

	private long id;
	private String description;
	private Set documentSharings = new HashSet(0);
	private Set documents = new HashSet(0);

	public DocumentWfStatus() {
	}

	public DocumentWfStatus(long id) {
		this.id = id;
	}

	public DocumentWfStatus(long id, String description, Set documentSharings,
			Set documents) {
		this.id = id;
		this.description = description;
		this.documentSharings = documentSharings;
		this.documents = documents;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDocumentSharings() {
		return this.documentSharings;
	}

	public void setDocumentSharings(Set documentSharings) {
		this.documentSharings = documentSharings;
	}

	public Set getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set documents) {
		this.documents = documents;
	}

}
