package ee.adit.dao;

// Generated 21.05.2010 14:11:24 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Document generated by hbm2java
 */
public class Document implements java.io.Serializable {

	private long id;
	private String guid;
	private String title;
	private String documentTypeShortName;
	private String creatorCode;
	private Date creationDate;
	private String remoteApplicationShortName;
	private Date lastModifiedDate;
	private Long documentDvkStatusId;
	private Long dvkId;
	private Long documentWorkflowStatusId;
	private Date lastAccessDate;
	private Long parentDocumentId;
	private Boolean locked;
	private Date lockingDate;
	private Boolean signable;
	private Boolean archived;
	private Date archivingDate;

	public Document() {
	}

	public Document(long id, String documentTypeShortName, String creatorCode) {
		this.id = id;
		this.documentTypeShortName = documentTypeShortName;
		this.creatorCode = creatorCode;
	}

	public Document(long id, String guid, String title,
			String documentTypeShortName, String creatorCode,
			Date creationDate, String remoteApplicationShortName,
			Date lastModifiedDate, Long documentDvkStatusId, Long dvkId,
			Long documentWorkflowStatusId, Date lastAccessDate,
			Long parentDocumentId, Boolean locked, Date lockingDate,
			Boolean signable, Boolean archived, Date archivingDate) {
		this.id = id;
		this.guid = guid;
		this.title = title;
		this.documentTypeShortName = documentTypeShortName;
		this.creatorCode = creatorCode;
		this.creationDate = creationDate;
		this.remoteApplicationShortName = remoteApplicationShortName;
		this.lastModifiedDate = lastModifiedDate;
		this.documentDvkStatusId = documentDvkStatusId;
		this.dvkId = dvkId;
		this.documentWorkflowStatusId = documentWorkflowStatusId;
		this.lastAccessDate = lastAccessDate;
		this.parentDocumentId = parentDocumentId;
		this.locked = locked;
		this.lockingDate = lockingDate;
		this.signable = signable;
		this.archived = archived;
		this.archivingDate = archivingDate;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDocumentTypeShortName() {
		return this.documentTypeShortName;
	}

	public void setDocumentTypeShortName(String documentTypeShortName) {
		this.documentTypeShortName = documentTypeShortName;
	}

	public String getCreatorCode() {
		return this.creatorCode;
	}

	public void setCreatorCode(String creatorCode) {
		this.creatorCode = creatorCode;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getRemoteApplicationShortName() {
		return this.remoteApplicationShortName;
	}

	public void setRemoteApplicationShortName(String remoteApplicationShortName) {
		this.remoteApplicationShortName = remoteApplicationShortName;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Long getDocumentDvkStatusId() {
		return this.documentDvkStatusId;
	}

	public void setDocumentDvkStatusId(Long documentDvkStatusId) {
		this.documentDvkStatusId = documentDvkStatusId;
	}

	public Long getDvkId() {
		return this.dvkId;
	}

	public void setDvkId(Long dvkId) {
		this.dvkId = dvkId;
	}

	public Long getDocumentWorkflowStatusId() {
		return this.documentWorkflowStatusId;
	}

	public void setDocumentWorkflowStatusId(Long documentWorkflowStatusId) {
		this.documentWorkflowStatusId = documentWorkflowStatusId;
	}

	public Date getLastAccessDate() {
		return this.lastAccessDate;
	}

	public void setLastAccessDate(Date lastAccessDate) {
		this.lastAccessDate = lastAccessDate;
	}

	public Long getParentDocumentId() {
		return this.parentDocumentId;
	}

	public void setParentDocumentId(Long parentDocumentId) {
		this.parentDocumentId = parentDocumentId;
	}

	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	public Date getLockingDate() {
		return this.lockingDate;
	}

	public void setLockingDate(Date lockingDate) {
		this.lockingDate = lockingDate;
	}

	public Boolean getSignable() {
		return this.signable;
	}

	public void setSignable(Boolean signable) {
		this.signable = signable;
	}

	public Boolean getArchived() {
		return this.archived;
	}

	public void setArchived(Boolean archived) {
		this.archived = archived;
	}

	public Date getArchivingDate() {
		return this.archivingDate;
	}

	public void setArchivingDate(Date archivingDate) {
		this.archivingDate = archivingDate;
	}

}
