package ee.adit.dao;

// Generated 21.05.2010 14:01:22 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.sql.Blob;

/**
 * DocumentFiles generated by hbm2java
 */
public class DocumentFiles implements java.io.Serializable {

	private long id;
	private long documentId;
	private String fileName;
	private String contentType;
	private String description;
	private Blob fileData;
	private BigDecimal fileSizeBytes;

	public DocumentFiles() {
	}

	public DocumentFiles(long id, long documentId, String fileName) {
		this.id = id;
		this.documentId = documentId;
		this.fileName = fileName;
	}

	public DocumentFiles(long id, long documentId, String fileName,
			String contentType, String description, Blob fileData,
			BigDecimal fileSizeBytes) {
		this.id = id;
		this.documentId = documentId;
		this.fileName = fileName;
		this.contentType = contentType;
		this.description = description;
		this.fileData = fileData;
		this.fileSizeBytes = fileSizeBytes;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(long documentId) {
		this.documentId = documentId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Blob getFileData() {
		return this.fileData;
	}

	public void setFileData(Blob fileData) {
		this.fileData = fileData;
	}

	public BigDecimal getFileSizeBytes() {
		return this.fileSizeBytes;
	}

	public void setFileSizeBytes(BigDecimal fileSizeBytes) {
		this.fileSizeBytes = fileSizeBytes;
	}

}
