package ee.adit.dao;

// Generated 11.05.2010 17:19:11 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentTypes generated by hbm2java
 */
public class DocumentTypes implements java.io.Serializable {

	private String documentTypeShortName;
	private String description;
	private Set documentses = new HashSet(0);

	public DocumentTypes() {
	}

	public DocumentTypes(String documentTypeShortName) {
		this.documentTypeShortName = documentTypeShortName;
	}

	public DocumentTypes(String documentTypeShortName, String description,
			Set documentses) {
		this.documentTypeShortName = documentTypeShortName;
		this.description = description;
		this.documentses = documentses;
	}

	public String getDocumentTypeShortName() {
		return this.documentTypeShortName;
	}

	public void setDocumentTypeShortName(String documentTypeShortName) {
		this.documentTypeShortName = documentTypeShortName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDocumentses() {
		return this.documentses;
	}

	public void setDocumentses(Set documentses) {
		this.documentses = documentses;
	}

}
