package ee.adit.dao;

// Generated 21.05.2010 14:01:22 by Hibernate Tools 3.2.4.GA

/**
 * DocumentWfStatuses generated by hbm2java
 */
public class DocumentWfStatuses implements java.io.Serializable {

	private long id;
	private String description;

	public DocumentWfStatuses() {
	}

	public DocumentWfStatuses(long id) {
		this.id = id;
	}

	public DocumentWfStatuses(long id, String description) {
		this.id = id;
		this.description = description;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
