package ee.adit.dao;

// Generated 11.05.2010 17:19:11 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentWorkflowStatuses generated by hbm2java
 */
public class DocumentWorkflowStatuses implements java.io.Serializable {

	private long documentWorkflowStatusId;
	private String description;
	private Set documentses = new HashSet(0);
	private Set documentSharingses = new HashSet(0);

	public DocumentWorkflowStatuses() {
	}

	public DocumentWorkflowStatuses(long documentWorkflowStatusId) {
		this.documentWorkflowStatusId = documentWorkflowStatusId;
	}

	public DocumentWorkflowStatuses(long documentWorkflowStatusId,
			String description, Set documentses, Set documentSharingses) {
		this.documentWorkflowStatusId = documentWorkflowStatusId;
		this.description = description;
		this.documentses = documentses;
		this.documentSharingses = documentSharingses;
	}

	public long getDocumentWorkflowStatusId() {
		return this.documentWorkflowStatusId;
	}

	public void setDocumentWorkflowStatusId(long documentWorkflowStatusId) {
		this.documentWorkflowStatusId = documentWorkflowStatusId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDocumentses() {
		return this.documentses;
	}

	public void setDocumentses(Set documentses) {
		this.documentses = documentses;
	}

	public Set getDocumentSharingses() {
		return this.documentSharingses;
	}

	public void setDocumentSharingses(Set documentSharingses) {
		this.documentSharingses = documentSharingses;
	}

}
