package ee.adit.dao;

// Generated 21.05.2010 14:11:24 by Hibernate Tools 3.2.4.GA

/**
 * DocumentType generated by hbm2java
 */
public class DocumentType implements java.io.Serializable {

	private String shortName;
	private String description;

	public DocumentType() {
	}

	public DocumentType(String shortName) {
		this.shortName = shortName;
	}

	public DocumentType(String shortName, String description) {
		this.shortName = shortName;
		this.description = description;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
