package ee.adit.dao;

// Generated 11.05.2010 17:19:11 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentSharingTypes generated by hbm2java
 */
public class DocumentSharingTypes implements java.io.Serializable {

	private String sharingTypeShortName;
	private String description;
	private Set documentSharingses = new HashSet(0);

	public DocumentSharingTypes() {
	}

	public DocumentSharingTypes(String sharingTypeShortName) {
		this.sharingTypeShortName = sharingTypeShortName;
	}

	public DocumentSharingTypes(String sharingTypeShortName,
			String description, Set documentSharingses) {
		this.sharingTypeShortName = sharingTypeShortName;
		this.description = description;
		this.documentSharingses = documentSharingses;
	}

	public String getSharingTypeShortName() {
		return this.sharingTypeShortName;
	}

	public void setSharingTypeShortName(String sharingTypeShortName) {
		this.sharingTypeShortName = sharingTypeShortName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDocumentSharingses() {
		return this.documentSharingses;
	}

	public void setDocumentSharingses(Set documentSharingses) {
		this.documentSharingses = documentSharingses;
	}

}
