package ee.adit.dao;

// Generated 27.05.2010 11:51:49 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentHistoryType generated by hbm2java
 */
public class DocumentHistoryType implements java.io.Serializable {

	private long id;
	private String description;
	private Set documentHistories = new HashSet(0);

	public DocumentHistoryType() {
	}

	public DocumentHistoryType(long id) {
		this.id = id;
	}

	public DocumentHistoryType(long id, String description,
			Set documentHistories) {
		this.id = id;
		this.description = description;
		this.documentHistories = documentHistories;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDocumentHistories() {
		return this.documentHistories;
	}

	public void setDocumentHistories(Set documentHistories) {
		this.documentHistories = documentHistories;
	}

}
