package ee.adit.dao;

// Generated 21.05.2010 14:01:22 by Hibernate Tools 3.2.4.GA

/**
 * NotificationTypes generated by hbm2java
 */
public class NotificationTypes implements java.io.Serializable {

	private String shortName;
	private String description;

	public NotificationTypes() {
	}

	public NotificationTypes(String shortName) {
		this.shortName = shortName;
	}

	public NotificationTypes(String shortName, String description) {
		this.shortName = shortName;
		this.description = description;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
