package ee.adit.dao;

// Generated 27.05.2010 11:51:49 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * NotificationType generated by hbm2java
 */
public class NotificationType implements java.io.Serializable {

	private String shortName;
	private String description;
	private Set userNotifications = new HashSet(0);

	public NotificationType() {
	}

	public NotificationType(String shortName) {
		this.shortName = shortName;
	}

	public NotificationType(String shortName, String description,
			Set userNotifications) {
		this.shortName = shortName;
		this.description = description;
		this.userNotifications = userNotifications;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getUserNotifications() {
		return this.userNotifications;
	}

	public void setUserNotifications(Set userNotifications) {
		this.userNotifications = userNotifications;
	}

}
