package ee.adit.dao;

// Generated 11.05.2010 17:19:11 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * RemoteApplications generated by hbm2java
 */
public class RemoteApplications implements java.io.Serializable {

	private String remoteApplicationShortName;
	private String remoteApplicationName;
	private String organizationCode;
	private boolean canRead;
	private boolean canWrite;
	private Set documentHistories = new HashSet(0);
	private Set accessRestrictionses = new HashSet(0);
	private Set documentses = new HashSet(0);

	public RemoteApplications() {
	}

	public RemoteApplications(String remoteApplicationShortName,
			boolean canRead, boolean canWrite) {
		this.remoteApplicationShortName = remoteApplicationShortName;
		this.canRead = canRead;
		this.canWrite = canWrite;
	}

	public RemoteApplications(String remoteApplicationShortName,
			String remoteApplicationName, String organizationCode,
			boolean canRead, boolean canWrite, Set documentHistories,
			Set accessRestrictionses, Set documentses) {
		this.remoteApplicationShortName = remoteApplicationShortName;
		this.remoteApplicationName = remoteApplicationName;
		this.organizationCode = organizationCode;
		this.canRead = canRead;
		this.canWrite = canWrite;
		this.documentHistories = documentHistories;
		this.accessRestrictionses = accessRestrictionses;
		this.documentses = documentses;
	}

	public String getRemoteApplicationShortName() {
		return this.remoteApplicationShortName;
	}

	public void setRemoteApplicationShortName(String remoteApplicationShortName) {
		this.remoteApplicationShortName = remoteApplicationShortName;
	}

	public String getRemoteApplicationName() {
		return this.remoteApplicationName;
	}

	public void setRemoteApplicationName(String remoteApplicationName) {
		this.remoteApplicationName = remoteApplicationName;
	}

	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	public boolean isCanRead() {
		return this.canRead;
	}

	public void setCanRead(boolean canRead) {
		this.canRead = canRead;
	}

	public boolean isCanWrite() {
		return this.canWrite;
	}

	public void setCanWrite(boolean canWrite) {
		this.canWrite = canWrite;
	}

	public Set getDocumentHistories() {
		return this.documentHistories;
	}

	public void setDocumentHistories(Set documentHistories) {
		this.documentHistories = documentHistories;
	}

	public Set getAccessRestrictionses() {
		return this.accessRestrictionses;
	}

	public void setAccessRestrictionses(Set accessRestrictionses) {
		this.accessRestrictionses = accessRestrictionses;
	}

	public Set getDocumentses() {
		return this.documentses;
	}

	public void setDocumentses(Set documentses) {
		this.documentses = documentses;
	}

}
