package ee.adit.dao;

// Generated 21.05.2010 14:11:24 by Hibernate Tools 3.2.4.GA

/**
 * UserNotification generated by hbm2java
 */
public class UserNotification implements java.io.Serializable {

	private UserNotificationId id;

	public UserNotification() {
	}

	public UserNotification(UserNotificationId id) {
		this.id = id;
	}

	public UserNotificationId getId() {
		return this.id;
	}

	public void setId(UserNotificationId id) {
		this.id = id;
	}

}
