package ee.adit.dao;

// Generated 27.05.2010 11:51:49 by Hibernate Tools 3.2.4.GA

/**
 * Usertype generated by hbm2java
 */
public class Usertype implements java.io.Serializable {

	private String shortName;
	private String description;

	public Usertype() {
	}

	public Usertype(String shortName) {
		this.shortName = shortName;
	}

	public Usertype(String shortName, String description) {
		this.shortName = shortName;
		this.description = description;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
