package ee.adit.dao;

// Generated 21.05.2010 14:01:22 by Hibernate Tools 3.2.4.GA

/**
 * UserNotificationsId generated by hbm2java
 */
public class UserNotificationsId implements java.io.Serializable {

	private String userCode;
	private String notificationTypeShortName;

	public UserNotificationsId() {
	}

	public UserNotificationsId(String userCode, String notificationTypeShortName) {
		this.userCode = userCode;
		this.notificationTypeShortName = notificationTypeShortName;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getNotificationTypeShortName() {
		return this.notificationTypeShortName;
	}

	public void setNotificationTypeShortName(String notificationTypeShortName) {
		this.notificationTypeShortName = notificationTypeShortName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserNotificationsId))
			return false;
		UserNotificationsId castOther = (UserNotificationsId) other;

		return ((this.getUserCode() == castOther.getUserCode()) || (this
				.getUserCode() != null
				&& castOther.getUserCode() != null && this.getUserCode()
				.equals(castOther.getUserCode())))
				&& ((this.getNotificationTypeShortName() == castOther
						.getNotificationTypeShortName()) || (this
						.getNotificationTypeShortName() != null
						&& castOther.getNotificationTypeShortName() != null && this
						.getNotificationTypeShortName().equals(
								castOther.getNotificationTypeShortName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserCode() == null ? 0 : this.getUserCode().hashCode());
		result = 37
				* result
				+ (getNotificationTypeShortName() == null ? 0 : this
						.getNotificationTypeShortName().hashCode());
		return result;
	}

}
