/*  -------------------------------------------------- */
/*  Generated by Enterprise Architect Version 7.5.844*/
/*  Created On : Friday, June 04, 2010 */
/*  DBMS       : Oracle */
/*  -------------------------------------------------- */

/* Create Tables */
CREATE TABLE &&ADIT_SCHEMA..ACCESS_RESTRICTION
(
	ID                  NUMBER(18) NOT NULL,	
	remote_application  VARCHAR2(50) NOT NULL,  /* Short name of remote application that uses ADIT for datastore. */
	user_code           VARCHAR2(50) NOT NULL,  /* Personal ID Code of user. */
	restriction         VARCHAR2(50)    		/* Type of restriction to be applied. "WRITE" - user/application cannot add, update or delete data; "READ" - user/application cannot read, add, update or delete any data. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..ACCESS_RESTRICTION IS 'Access restrictions for user-application combination. Infosüsteemidele saab määrata piiranguid kasutajate nimel tegevuste läbi viimiseks rakenduses.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ACCESS_RESTRICTION.remote_application  IS 'Short name of remote application that uses ADIT for datastore.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ACCESS_RESTRICTION.user_code           IS 'Personal ID Code of user.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ACCESS_RESTRICTION.restriction         IS 'Type of restriction to be applied. "WRITE" - user/application cannot add, update or delete data; "READ" - user/application cannot read, add, update or delete any data.';

CREATE TABLE &&ADIT_SCHEMA..ADIT_LOG
(
	ID                             NUMBER(18) NOT NULL,
	table_name                     VARCHAR2(50),    /* Muutunud väärtuse tabeli nimi */
	column_name                    VARCHAR2(50),    /* Muutunud väärtuse tabeli veeru nimi */
	old_value                      VARCHAR2(4000),    /* Vana väärtus */
	new_value                      VARCHAR2(4000),    /* Uus väärtus */
	log_date                       DATE,    /* Muudatuse aeg */
	primary_key_value			   VARCHAR2(100), 	/* Primaarvõtme väärtus */
	remote_application_short_name  VARCHAR2(50),    /* Infosüsteem, kes antud muudatuse välja kutsus. */
	xtee_user_code                 VARCHAR2(50),    /* X-tee päringu isikukood */
	xtee_institution_code          VARCHAR2(50),    /* X-tee päringu ettevõtte registrikood */
	db_user                        VARCHAR2(50)    /* Andmebaasikasutaja nimi. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..ADIT_LOG IS 'Andmed kõikide andmebaasis tehtud muudatuste kohta. Välja arvatud tabeli DOCUMENT_FILES veeru FILE_DATA muudatused.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_LOG.table_name                     IS 'Muutunud väärtuse tabeli nimi';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_LOG.column_name                    IS 'Muutunud väärtuse tabeli veeru nimi';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_LOG.old_value                      IS 'Vana väärtus';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_LOG.new_value                      IS 'Uus väärtus';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_LOG.log_date                       IS 'Muudatuse aeg';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_LOG.remote_application_short_name  IS 'Infosüsteem, kes antud muudatuse välja kutsus.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_LOG.xtee_user_code                 IS 'X-tee päringu isikukood';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_LOG.xtee_institution_code          IS 'X-tee päringu ettevõtte registrikood';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_LOG.db_user                        IS 'Andmebaasikasutaja nimi.';

CREATE TABLE &&ADIT_SCHEMA..ADIT_USER
(
	user_code                   VARCHAR2(50) NOT NULL,    /* Kasutaja isiku või registrikood koos riigitunnusega. Nt. "EE38407089945". */
	full_name                   VARCHAR2(255),    /* Kasutaja täispikk nimi. */
	usertype                    VARCHAR2(50) NOT NULL,    /* Viide kasutaja tüübile. */
	active                      NUMBER(1) DEFAULT 1,    /* Näitab, kas tegemist on aktiivse kasutajaga. "1" - aktiivne", "0" - mitteaktiivne. */
	dvk_org_code                VARCHAR2(50),    /* Kui kasutaja kasutab dokumentide saatmiseks ja vastuvõtmiseks DVK-d, siis on see väli täidetud. Väljale kirjutatakse kasutaja DVK asutuse registrikood. */
	dvk_subdivision_short_name  VARCHAR2(50),    /* Kui kasutaja kasutab dokumentide saatmiseks ja vastuvõtmiseks DVK-d, siis on see väli täidetud juhul kui asutusel on DVK-s registreeritud vastav allüksus. Väljale kirjutatakse kasutaja DVK asutuse allüksuse lühinimi. */
	dvk_occupation_short_name   VARCHAR2(50),    /* Kui kasutaja kasutab dokumentide saatmiseks ja vastuvõtmiseks DVK-d, siis on see väli täidetud juhul kui asutusel on DVK-s registreeritud vastav ametikoht. Väljale kirjutatakse kasutaja DVK asutuse ametikoha lühinimi. */
	disk_quota                  NUMBER(18),    /* Kasutaja failide mahupiirang baitides. Kasutajale määratud mahupiirang omab prioriteeti kasutajatüübi mahupiirangu üle. */
	deactivation_date			DATE	/* Kasutajakonto kustutamise / deaktiveerimise kellaaeg ja kuupäev */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..ADIT_USER IS 'Kasutaja andmed. Kasutaja on alati isik, kelle määrab üheselt isikukood. Isik võib süsteemis esindada kas iseennast või asutust.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_USER.user_code                   IS 'Kasutaja isiku või registrikood koos riigitunnusega. Nt. "EE38407089945".';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_USER.full_name                   IS 'Kasutaja täispikk nimi.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_USER.usertype                    IS 'Viide kasutaja tüübile.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_USER.active                      IS 'Näitab, kas tegemist on aktiivse kasutajaga. "1" - aktiivne", "0" - mitteaktiivne.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_USER.dvk_org_code                IS 'Kui kasutaja kasutab dokumentide saatmiseks ja vastuvõtmiseks DVK-d, siis on see väli täidetud. Väljale kirjutatakse kasutaja DVK asutuse registrikood.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_USER.dvk_subdivision_short_name  IS 'Kui kasutaja kasutab dokumentide saatmiseks ja vastuvõtmiseks DVK-d, siis on see väli täidetud juhul kui asutusel on DVK-s registreeritud vastav allüksus. Väljale kirjutatakse kasutaja DVK asutuse allüksuse lühinimi.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_USER.dvk_occupation_short_name   IS 'Kui kasutaja kasutab dokumentide saatmiseks ja vastuvõtmiseks DVK-d, siis on see väli täidetud juhul kui asutusel on DVK-s registreeritud vastav ametikoht. Väljale kirjutatakse kasutaja DVK asutuse ametikoha lühinimi.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ADIT_USER.disk_quota                  IS 'Kasutaja failide mahupiirang baitides. Kasutajale määratud mahupiirang omab prioriteeti kasutajatüübi mahupiirangu üle.';

CREATE TABLE &&ADIT_SCHEMA..DOCUMENT
(
	ID                      NUMBER(12) NOT NULL,    /* Unikaalne identifikaator */
	guid                    VARCHAR2(50),    /* Dokumendi globaalselt unikaalne identifikaator. Kui dokument võetakse vastu DVK-st, siis tuleb ka GUID sealt. Kui dokument luuakse ADIT-is, siis genereerib ADIT ise GUID. */
	title                   VARCHAR2(255),    /* Dokumendi pealkiri. */
	type                    VARCHAR2(50) NOT NULL,    /* Viide dokumendi tüübi lühinimele. */
	creator_code            VARCHAR2(50) NOT NULL,    /* Dokumendi looja isikukood. */
	creator_name            VARCHAR2(255) NULL,    /* Dokumendi looja nimi (loomise hetke seisuga) */
	creator_user_code       VARCHAR2(50) NULL,    /* Dokumendi loonud isiku isikukood (juhul, kui dokument kuulub asutusele). */
	creator_user_name       VARCHAR2(255) NULL,    /* Dokumendi loonud isiku nimi (juhul, kui dokument kuulub asutusele; loomise hetke seisuga) */
	creation_date           DATE,    /* Dokumendi loomise kuupäev ja kellaaeg */
	remote_application      VARCHAR2(50),    /* Viide päringu välja kutsunud infosüsteemi lühinimele. */
	last_modified_date      DATE,    /* Viimase muudatuse kuupäev ja kellaaeg. */
	document_dvk_status_id  NUMBER(12),    /* Kui dokument on saadetud üle DVK või võetud vastu DVK-st, siis kirjutatakse siia väljale dokumendi DVK staatuse idenfitikaator */
	dvk_id                  NUMBER(12),    /* Kui tegemist on DVK-st tulnud dokumendiga, siis kirjutatakse siia dokumendile DVK poolt antud ID */
	document_wf_status_id   NUMBER(12),    /* Viide dokumendi töövoo staatusele. */
	parent_id               NUMBER(12),    /* Kui on tegemist alamdokumendiga, siis viide nn peadokumendile */
	locked                  NUMBER(1) DEFAULT 0,    /* Näitab, kas dokument on "lukustatud". "1" - lukus, "0" - lukustamata. */
	locking_date            DATE,    /* Lukustamise kuupäev ja kellaaeg */
	signable                NUMBER(1) DEFAULT 0,    /* Näitab, kas dokument on allkirjastatav. */
	deflated                NUMBER(1) DEFAULT 0,    /* Näitab, kas dokument on arhiveeritud. "1" - arhiveeritud, "0" - ei ole arhiveeritud */
	deflate_date            DATE,    /* Arhiveerimise kuupäev ja kellaaeg. */
	deleted                 NUMBER(1),    /* Näitab, kas dokument on kustutatud. "1" - kustutatud, "0" - kustutamata. */
	signature_container		BLOB	/* Digitaalallkirja konteiner (ddoc või bdoc fail) */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..DOCUMENT IS 'Dokumendi andmed.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.ID                      IS 'Unikaalne identifikaator';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.guid                    IS 'Dokumendi globaalselt unikaalne identifikaator. Kui dokument võetakse vastu DVK-st, siis tuleb ka GUID sealt. Kui dokument luuakse ADIT-is, siis genereerib ADIT ise GUID.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.title                   IS 'Dokumendi pealkiri.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.type                    IS 'Viide dokumendi tüübi lühinimele.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.creator_code            IS 'Dokumendi looja isikukood.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.creator_name            IS 'Dokumendi looja nimi (loomise hetke seisuga)';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.creator_user_code       IS 'Dokumendi loonud isiku isikukood (juhul, kui dokument kuulub asutusele).';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.creator_user_name       IS 'Dokumendi loonud isiku nimi (juhul, kui dokument kuulub asutusele; loomise hetke seisuga)';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.creation_date           IS 'Dokumendi loomise kuupäev ja kellaaeg';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.remote_application      IS 'Viide päringu välja kutsunud infosüsteemi lühinimele.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.last_modified_date      IS 'Viimase muudatuse kuupäev ja kellaaeg.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.document_dvk_status_id  IS 'Kui dokument on saadetud üle DVK või võetud vastu DVK-st, siis kirjutatakse siia väljale dokumendi DVK staatuse idenfitikaator';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.dvk_id                  IS 'Kui tegemist on DVK-st tulnud dokumendiga, siis kirjutatakse siia dokumendile DVK poolt antud ID';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.document_wf_status_id   IS 'Viide dokumendi töövoo staatusele.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.parent_id               IS 'Kui on tegemist alamdokumendiga, siis viide nn peadokumendile';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.locked                  IS 'Näitab, kas dokument on "lukustatud". "1" - lukus, "0" - lukustamata.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.locking_date            IS 'Lukustamise kuupäev ja kellaaeg';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.signable                IS 'Näitab, kas dokument on allkirjastatav.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.deflated                IS 'Näitab, kas dokument on arhiveeritud. "1" - arhiveeritud, "0" - ei ole arhiveeritud';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.deflate_date            IS 'Arhiveerimise kuupäev ja kellaaeg.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.deleted                 IS 'Näitab, kas dokument on kustutatud. "1" - kustutatud, "0" - kustutamata.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT.signature_container     IS 'Digitaalallkirja konteiner (ddoc või bdoc fail)';

CREATE TABLE &&ADIT_SCHEMA..DOCUMENT_DVK_STATUS
(
	ID           NUMBER(12) NOT NULL,    /* DVK staatuse unikaalne identifikaator */
	description  VARCHAR2(4000)    /* DVK staatuse kirjeldus */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..DOCUMENT_DVK_STATUS IS 'Dokumendi DVK staatused (kattuvad DVK staatustega). Staatused on järgmised: 
 1. Puudub (100) 2. Saatmisel (101) 3. Saadetud (102) 4. Katkestatud (103)';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_DVK_STATUS.ID           IS 'DVK staatuse unikaalne identifikaator';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_DVK_STATUS.description  IS 'DVK staatuse kirjeldus';

CREATE TABLE &&ADIT_SCHEMA..DOCUMENT_FILE
(
	ID               NUMBER(12) NOT NULL,    /* Unikaalne identifikaator */
	document_id      NUMBER(12) NOT NULL,    /* Viide dokumendi ID-le */
	file_name        VARCHAR2(255) NOT NULL,    /* Faili nimi. (Nt. "avaldus.doc") */
	content_type     VARCHAR2(255),    /* Faili MIME tüüp. (Nt. "application/rtf") */
	description      VARCHAR2(4000),    /* Faili kirjeldus. */
	file_data        BLOB,    /* Faili sisu binaarkujul */
	file_size_bytes  NUMBER(38),    /* Faili suurus baitides */
	deleted          NUMBER(1) DEFAULT 0 /* Kas antud fail on kustutatud */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..DOCUMENT_FILE IS 'Dokumendi juurde kuuluvate failide andmed.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_FILE.ID               IS 'Unikaalne identifikaator';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_FILE.document_id      IS 'Viide dokumendi ID-le';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_FILE.file_name        IS 'Faili nimi. (Nt. "avaldus.doc")';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_FILE.content_type     IS 'Faili MIME tüüp. (Nt. "application/rtf")';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_FILE.description      IS 'Faili kirjeldus.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_FILE.file_data        IS 'Faili sisu binaarkujul';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_FILE.file_size_bytes  IS 'Faili suurus baitides';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_FILE.deleted          IS 'Kas antud fail on kustutatud';

CREATE TABLE &&ADIT_SCHEMA..DOCUMENT_HISTORY
(
	ID                     NUMBER(12) NOT NULL,    /* Unikaalne identifikaator */
	document_id            NUMBER(12) NOT NULL,    /* Viide dokumendile, millega ajalookirje on seotud */
	document_history_type  VARCHAR2(50),    /* Viide dokumendi ajaloo tüübile. */
	description            VARCHAR2(4000),    /* Toimingu täpsem kirjeldus, kui vajalik. */
	event_date             DATE,    /* Tegevuse kuupäev ja kelaaaeg */
	user_code              VARCHAR2(50),    /* Tegevuse läbi viinud kasutaja kood. Viide kasutajale. */
	user_name              VARCHAR2(255),    /* Tegevuse läbi viinud kasutaja nimi (tegevuse toimumise hetke seisuga). */
	remote_application     VARCHAR2(50),    /* Viide välisele infosüsteemile (välise infosüsteemi lühinimi), mis antud toimingu välja kutsus. */
	notification_status    VARCHAR2(50),    /* Teavituse saatmise staatus. Kui teavistus on saatmata, siis "SAADA", kui saadetud, siis "SAADETUD". Kui teavitust ei ole vaja saata, siis väli tühi (NULL). */
	xtee_notification_id   VARCHAR2(50),    /* Teavituskalendri X-tee teenuselt saadud teavituse ID. See väli täidetakse juhul kui teavituse saatmine teavituskalendrile õnnestus. */
	xtee_user_code         VARCHAR2(50),    /* X-tee kasutaja isikukood, kes tegevuse käivitas. See on vajalik selleks, et asutuse dokumentide puhul teada, milline konkreetne isik tegevuse läbi viis. */
	xtee_user_name         VARCHAR2(255)    /* X-tee kasutaja nimi (kui oli võimalik tuvastada) */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..DOCUMENT_HISTORY IS 'Dokumendi ajalookirjed. Kirje tekib siis, kui dokumendiga viiakse läbi toiming. Tabel koondab endasse dokumendiga teostatud toimingute ajaloo.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.ID                     IS 'Unikaalne identifikaator';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.document_id            IS 'Viide dokumendile, millega ajalookirje on seotud';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.document_history_type  IS 'Viide dokumendi ajaloo tüübile.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.description            IS 'Toimingu täpsem kirjeldus, kui vajalik.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.event_date             IS 'Tegevuse kuupäev ja kelaaaeg';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.user_code              IS 'Tegevuse läbi viinud isiku kood. Viide kasutajale.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.user_name              IS 'Tegevuse läbi viinud kasutaja nimi (tegevuse toimumise hetke seisuga).';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.remote_application     IS 'Viide välisele infosüsteemile (välise infosüsteemi lühinimi), mis antud toimingu välja kutsus.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.notification_status    IS 'Teavituse saatmise staatus. Kui teavistus on saatmata, siis "SAADA", kui saadetud, siis "SAADETUD". Kui teavitust ei ole vaja saata, siis väli tühi (NULL).';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.xtee_notification_id   IS 'Teavituskalendri X-tee teenuselt saadud teavituse ID. See väli täidetakse juhul kui teavituse saatmine teavituskalendrile õnnestus.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.xtee_user_code         IS 'X-tee kasutaja isikukood, kes tegevuse käivitas. See on vajalik selleks, et asutuse dokumentide puhul teada, milline konkreetne isik tegevuse läbi viis.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY.xtee_user_name         IS 'X-tee kasutaja nimi (kui oli võimalik tuvastada)';

CREATE TABLE &&ADIT_SCHEMA..DOCUMENT_HISTORY_TYPE
(
	short_name   VARCHAR2(50) NOT NULL,    /* Ajalookirje tüübi nimi. Nt. "esmane loomine" või "dokumendi muutmine". */
	description  VARCHAR2(4000)    /* Ajalookirje tüübi kirjeldus. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..DOCUMENT_HISTORY_TYPE IS 'Dokumendi ajalookirjete tüübid. Ajalookirjete tüübid on näiteks "esmane loomine", "dokumendi muutmine" jne. (täpsemalt on kirjeldatud dokumentatsioonis). Ajalookirjete tüübid on järgmised: 
 1. Esmane loomine 2. Dokumendi muutmine 3. Dokumendi faili lisamine 4. Dokumendi faili muutmine 5. Dokumendi faili kustutamine 6. Staatuse muutmine 7. Saatmine 8. Jagamine 9. Lukustamine 10. Arhiveerimine 11. Dokumendi digitaalne allkirjastamine 12. Kustutamine';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY_TYPE.short_name   IS 'Ajalookirje tüübi nimi. Nt. "esmane loomine" või "dokumendi muutmine".';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_HISTORY_TYPE.description  IS 'Ajalookirje tüübi kirjeldus.';

CREATE TABLE &&ADIT_SCHEMA..DOCUMENT_SHARING
(
	ID                NUMBER(12) NOT NULL,    /* Unikaalne identifikaator */
	document_id       NUMBER(12) NOT NULL,    /* Viide dokumendile */
	user_code         VARCHAR2(50) NOT NULL,    /* Viide kasutajale (isikukood), kellele dokument jagati */
	user_name		  VARCHAR2(255) NULL,		/* Kasutaja nimi (jagamise hetke seisuga) */
	sharing_type      VARCHAR2(50) NOT NULL,    /* Viide dokumendi jagamise tüübile. Viidatakse kasutades dokumendi tüübi lühinime. */
	task_description  VARCHAR2(4000),    /* Jagamise eesmärk. Toiming, mida jagamise adressaat peaks dokumendiga tegema. */
	creation_date     DATE,    /* Jagamise kuupäev ja kellaaeg */
	dvk_status_id     NUMBER(12),    /* Dokumendi DVK staatuse ID. Näitab, millises staatuses on jagatud dokument adressaadi DVK-s. */
	wf_status_id      NUMBER(12),    /* Töövoo staatuse ID */
	last_access_date  DATE    /* Kuupäev ja kellaaeg, millal viimati jagatud dokumendi andmeid vaadati. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..DOCUMENT_SHARING IS 'Dokumendi jagamise andmed.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING.ID                IS 'Unikaalne identifikaator';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING.document_id       IS 'Viide dokumendile';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING.user_code         IS 'Viide kasutajale (isikukood), kellele dokument jagati';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING.user_name         IS 'Kasutaja nimi (jagamise hetke seisuga)';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING.sharing_type      IS 'Viide dokumendi jagamise tüübile. Viidatakse kasutades dokumendi tüübi lühinime.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING.task_description  IS 'Jagamise eesmärk. Toiming, mida jagamise adressaat peaks dokumendiga tegema.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING.creation_date     IS 'Jagamise kuupäev ja kellaaeg';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING.dvk_status_id     IS 'Dokumendi DVK staatuse ID. Näitab, millises staatuses on jagatud dokument adressaadi DVK-s.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING.wf_status_id      IS 'Töövoo staatuse ID';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING.last_access_date  IS 'Kuupäev ja kellaaeg, millal viimati jagatud dokumendi andmeid vaadati.';

CREATE TABLE &&ADIT_SCHEMA..DOCUMENT_SHARING_TYPE
(
	short_name   VARCHAR2(50) NOT NULL,    /* Dokumendi jagamise tüübi lühinimi. (Nt. "sending", "sharing"). Lühinimed on inglisekeelsed. */
	description  VARCHAR2(4000)    /* Dokumendi jagamise tüübi kirjeldus. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..DOCUMENT_SHARING_TYPE IS 'Dokumendi jagamise tüübid: 
 1. Allkirjastamine 2. Jagamine 3. DVK Saatmine 4. ADIT Saatmine';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING_TYPE.short_name   IS 'Dokumendi jagamise tüübi lühinimi. (Nt. "sending", "sharing"). Lühinimed on inglisekeelsed.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_SHARING_TYPE.description  IS 'Dokumendi jagamise tüübi kirjeldus.';

CREATE TABLE &&ADIT_SCHEMA..DOCUMENT_TYPE
(
	short_name   VARCHAR2(50) NOT NULL,    /* Dokumendi tüübi lühinimi. */
	description  VARCHAR2(4000)    /* Dokumendi tüübi kirjeldus. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..DOCUMENT_TYPE IS 'Dokumendi tüüpide kirjeldused. Neid liike lisandub töö käigus, kuid esialgselt on olemas: 
 1. Kiri (letter) 2. Avaldus / Taotlus (application)';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_TYPE.short_name   IS 'Dokumendi tüübi lühinimi.';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_TYPE.description  IS 'Dokumendi tüübi kirjeldus.';

CREATE TABLE &&ADIT_SCHEMA..DOCUMENT_WF_STATUS
(
	ID           NUMBER(12) NOT NULL,    /* Unikaalne identifikaator */
	description  VARCHAR2(4000),    /* Töövoo staatuse kirjeldus */
	name         VARCHAR2(50)    /* Dokumendi töövoo staatuse nimetus. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..DOCUMENT_WF_STATUS IS 'Töövoo staatused. Staatused on järgmised: 
 1. Puudub (lokaalse faili puhul) 2. Dokumente on puudu 3. Järjekorras 4. Ootel 5. Lõpetatud 6. Tagasi lükatud 7. Teha 8. Töötlemisel 9. Aktsepteeritud (võetud töösse) 10. Salvestatud 11. Arhiveeritud 12. Saadetud';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_WF_STATUS.ID           IS 'Unikaalne identifikaator';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_WF_STATUS.description  IS 'Töövoo staatuse kirjeldus';
COMMENT ON COLUMN &&ADIT_SCHEMA..DOCUMENT_WF_STATUS.name         IS 'Dokumendi töövoo staatuse nimetus.';

CREATE TABLE &&ADIT_SCHEMA..DOWNLOAD_REQUEST_LOG
(
	ID                             NUMBER(18) NOT NULL,
	document_id                    NUMBER(12),
	document_file_id               NUMBER(12),
	request_date                   DATE,
	remote_application_short_name  VARCHAR2(50),
	user_code                      VARCHAR2(50),
	organization_code              VARCHAR2(50)
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..DOWNLOAD_REQUEST_LOG IS 'Allalaadimispäringute logi. Siia tabelisse kirjutatakse andmed juhul kui käivitatakse üks järgmistest päringutest: 
 - getDocument (juhul kui päringu parameetri "kas tagastada ka failide sisu" väärtuseks on "jah") - getDocumentFile';

CREATE TABLE &&ADIT_SCHEMA..ERROR_LOG
(
	ID                             NUMBER(18) NOT NULL,
	document_id                    NUMBER(12),    /* Dokument, mille töötlemisel või millega seotud tegevuse ebaõnnestumisel viga tekkis. */
	error_date                     DATE,    /* Vea tekkimise aeg */
	remote_application_short_name  VARCHAR2(50),    /* Päringu teinud infosüsteemi lühinimi. */
	user_code                      VARCHAR2(50),    /* Päringuga seotud isiku kood */
	action_name                    VARCHAR2(255),    /* Päringu või toimingu nimi, mille täitmisel viga ilmnes. */
	error_level                    VARCHAR2(50),    /* Vea raskusaste (FATAL, ERROR, WARNING) */
	error_message                  VARCHAR2(4000)    /* Veateate sisu */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON COLUMN &&ADIT_SCHEMA..ERROR_LOG.document_id                    IS 'Dokument, mille töötlemisel või millega seotud tegevuse ebaõnnestumisel viga tekkis.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ERROR_LOG.error_date                     IS 'Vea tekkimise aeg';
COMMENT ON COLUMN &&ADIT_SCHEMA..ERROR_LOG.remote_application_short_name  IS 'Päringu teinud infosüsteemi lühinimi.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ERROR_LOG.user_code                      IS 'Päringuga seotud isiku kood';
COMMENT ON COLUMN &&ADIT_SCHEMA..ERROR_LOG.action_name                    IS 'Päringu või toimingu nimi, mille täitmisel viga ilmnes.';
COMMENT ON COLUMN &&ADIT_SCHEMA..ERROR_LOG.error_level                    IS 'Vea raskusaste (FATAL, ERROR, WARNING)';
COMMENT ON COLUMN &&ADIT_SCHEMA..ERROR_LOG.error_message                  IS 'Veateate sisu';

CREATE TABLE &&ADIT_SCHEMA..METADATA_REQUEST_LOG
(
	ID                             NUMBER(18) NOT NULL,
	document_id                    NUMBER(12) NOT NULL,    /* Dokumendi ID, mida vaadati. */
	request_date                   DATE,    /* Päringu tegemise aeg. */
	remote_application_short_name  VARCHAR2(50),    /* Päringu teinud infosüsteemi lühinimi. */
	user_code                      VARCHAR2(50),    /* Isik, kelle nimel päring tehti (kas eraisikuna või juriidilise isiku esindajana) */
	organization_code              VARCHAR2(50)    /* Juriidilise isiku registrikood */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..METADATA_REQUEST_LOG IS 'Dokumendi ja metaandmete päringute logi. Andmed kirjutatakse siia tabelisse juhul kui käivitatakse üks järgmistest päringutest: 
 - getDocumentList - getDocument';
COMMENT ON COLUMN &&ADIT_SCHEMA..METADATA_REQUEST_LOG.document_id                    IS 'Dokumendi ID, mida vaadati.';
COMMENT ON COLUMN &&ADIT_SCHEMA..METADATA_REQUEST_LOG.request_date                   IS 'Päringu tegemise aeg.';
COMMENT ON COLUMN &&ADIT_SCHEMA..METADATA_REQUEST_LOG.remote_application_short_name  IS 'Päringu teinud infosüsteemi lühinimi.';
COMMENT ON COLUMN &&ADIT_SCHEMA..METADATA_REQUEST_LOG.user_code                      IS 'Isik, kelle nimel päring tehti (kas eraisikuna või juriidilise isiku esindajana)';
COMMENT ON COLUMN &&ADIT_SCHEMA..METADATA_REQUEST_LOG.organization_code              IS 'Juriidilise isiku registrikood';

CREATE TABLE &&ADIT_SCHEMA..NOTIFICATION_TYPE
(
	short_name   VARCHAR2(50) NOT NULL,    /* Teavituse tüübi lühinimi */
	description  VARCHAR2(4000)    /* Teavituse tüübi kirjeldus. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..NOTIFICATION_TYPE IS 'Teavituste tüüpide andmed. Teavituse tübid on järgmised: 
 1. Saatmine (send) 2. Jagamine (share) 3. Vaatamine (view) 4. Muutmine (modify) 5. Allkirjastamine (sign)';
COMMENT ON COLUMN &&ADIT_SCHEMA..NOTIFICATION_TYPE.short_name   IS 'Teavituse tüübi lühinimi';
COMMENT ON COLUMN &&ADIT_SCHEMA..NOTIFICATION_TYPE.description  IS 'Teavituse tüübi kirjeldus.';

CREATE TABLE &&ADIT_SCHEMA..REMOTE_APPLICATION
(
	short_name         VARCHAR2(50) NOT NULL,    /* Infosüsteemi lühinimi */
	name               VARCHAR2(50),    /* Infosüsteemi täispikk nimi */
	organization_code  VARCHAR2(50) NOT NULL,    /* Infosüsteemi omaniku (asutuse) registrikood */
	can_read           NUMBER(1) DEFAULT 0,    /* Näitab, kas infosüsteemil on üleüldine õigus rakenduse abil andmeid lugeda. */
	can_write          NUMBER(1) DEFAULT 0    /* Näitab, kas infosüsteemil on üleüldine õigus rakenduse abil andmeid muuta. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..REMOTE_APPLICATION IS 'Välised infosüsteemid.';
COMMENT ON COLUMN &&ADIT_SCHEMA..REMOTE_APPLICATION.short_name         IS 'Infosüsteemi lühinimi';
COMMENT ON COLUMN &&ADIT_SCHEMA..REMOTE_APPLICATION.name               IS 'Infosüsteemi täispikk nimi';
COMMENT ON COLUMN &&ADIT_SCHEMA..REMOTE_APPLICATION.organization_code  IS 'Infosüsteemi omaniku (asutuse) registrikood';
COMMENT ON COLUMN &&ADIT_SCHEMA..REMOTE_APPLICATION.can_read           IS 'Näitab, kas infosüsteemil on üleüldine õigus rakenduse abil andmeid lugeda.';
COMMENT ON COLUMN &&ADIT_SCHEMA..REMOTE_APPLICATION.can_write          IS 'Näitab, kas infosüsteemil on üleüldine õigus rakenduse abil andmeid muuta.';

CREATE TABLE &&ADIT_SCHEMA..REQUEST_LOG
(
	ID                             NUMBER(18) NOT NULL,
	request                        VARCHAR2(50),    /* Päringu nimi. Nt. "shareDocument" */
	document_id                    NUMBER(12),    /* Dokumendi ID, millega tegevus läbi viidi */
	request_date                   DATE,    /* Päringu tegemise aeg */
	remote_application_short_name  VARCHAR2(50),    /* Päringu teinud infosüsteemi lühinimi */
	user_code                      VARCHAR2(50),    /* Isik, kelle nimel päring tehti (kas eraisikuna või juriidilise isiku esindajana) */
	organization_code              VARCHAR2(50),    /* Juriidilise isiku registrikood */
	additional_information         VARCHAR2(4000)    /* Lisainfo päringu kohta. Nt. "saveDocumentFile" päringu puhul kirjutatakse siia ka manuse ID. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..REQUEST_LOG IS 'Päringute tehtud muudatuste logi. Andmed kirjutatakse sellesse tabelisse juhul, kui käivitati üks järgmistest päringutest: 
 - saveDocument - saveDocumentFile - deleteDocumentFile - archieveDocument - deleteDocument - getDocumentHistory - sendDocument - shareDocument - unShareDocument - markDocumentViewed - prepareSignature - giveSiganture - modifyStatus';
COMMENT ON COLUMN &&ADIT_SCHEMA..REQUEST_LOG.request                        IS 'Päringu nimi. Nt. "shareDocument"';
COMMENT ON COLUMN &&ADIT_SCHEMA..REQUEST_LOG.document_id                    IS 'Dokumendi ID, millega tegevus läbi viidi';
COMMENT ON COLUMN &&ADIT_SCHEMA..REQUEST_LOG.request_date                   IS 'Päringu tegemise aeg';
COMMENT ON COLUMN &&ADIT_SCHEMA..REQUEST_LOG.remote_application_short_name  IS 'Päringu teinud infosüsteemi lühinimi';
COMMENT ON COLUMN &&ADIT_SCHEMA..REQUEST_LOG.user_code                      IS 'Isik, kelle nimel päring tehti (kas eraisikuna või juriidilise isiku esindajana)';
COMMENT ON COLUMN &&ADIT_SCHEMA..REQUEST_LOG.organization_code              IS 'Juriidilise isiku registrikood';
COMMENT ON COLUMN &&ADIT_SCHEMA..REQUEST_LOG.additional_information         IS 'Lisainfo päringu kohta. Nt. "saveDocumentFile" päringu puhul kirjutatakse siia ka manuse ID.';

CREATE TABLE &&ADIT_SCHEMA..SIGNATURE
(
	ID              NUMBER(12) NOT NULL,    /* Unikaalne identifikaator. */
	user_code       VARCHAR2(50),    /* Viide kasutajale, kes allkirja andis. */
	document_id     NUMBER(12) NOT NULL,    /* Viide dokumendile, millele allkiri anti. */
	signer_role     VARCHAR2(50),    /* Allkirja metaandmed - roll */
	resolution      VARCHAR2(100),    /* Allkirja metaandmed - resolutsioon */
	country         VARCHAR2(100),    /* Allkirja metaandmed - riik */
	county          VARCHAR2(100),    /* Allkirja metaandmed - maakond */
	city            VARCHAR2(100),    /* Allkirja metaandmed - linn */
	post_index      VARCHAR2(50),    /* Allkirja metaandmed - indeks */
	signer_code		VARCHAR2(20),    /* Allkirja metaandmed - allkirjastaja isikukood */
	signer_name		VARCHAR2(255),   /* Allkirja metaandmed - allkirjastaja nimi */
	signing_date    DATE				/* Allkirja andmise kuupäev ja kellaaeg */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..SIGNATURE IS 'Allkirjade tabel.';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.ID              IS 'Unikaalne identifikaator.';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.user_code       IS 'Viide kasutajale, kes allkirja andis.';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.document_id     IS 'Viide dokumendile, millele allkiri anti.';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.signer_role     IS 'Allkirja metaandmed - roll';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.resolution      IS 'Allkirja metaandmed - resolutsioon';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.country         IS 'Allkirja metaandmed - riik';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.county          IS 'Allkirja metaandmed - maakond';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.city            IS 'Allkirja metaandmed - linn';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.post_index      IS 'Allkirja metaandmed - indeks';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.signer_code     IS 'Allkirja metaandmed - allkirjastaja isikukood';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.signer_name     IS 'Allkirja metaandmed - allkirjastaja nimi';
COMMENT ON COLUMN &&ADIT_SCHEMA..SIGNATURE.signing_date    IS 'Allkirja andmise kuupäev ja kellaaeg';

CREATE TABLE &&ADIT_SCHEMA..USER_NOTIFICATION
(
	user_code          VARCHAR2(50) NOT NULL,    /* Viide kasutajale (isiku- või registrikood) */
	notification_type  VARCHAR2(50) NOT NULL    /* Teavituse tüübi lühinimi. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..USER_NOTIFICATION IS 'Kasutajate teavituste andmed. Kasutaja saab määrata, kas ta soovib teatud sündmuste toimumisel saada teavitusi. Teavitused edastatakse teavituskalendrile vastavalt selles tabelis olevale seadistusele.';
COMMENT ON COLUMN &&ADIT_SCHEMA..USER_NOTIFICATION.user_code          IS 'Viide kasutajale (isiku- või registrikood)';
COMMENT ON COLUMN &&ADIT_SCHEMA..USER_NOTIFICATION.notification_type  IS 'Teavituse tüübi lühinimi.';

CREATE TABLE &&ADIT_SCHEMA..USERTYPE
(
	short_name   VARCHAR2(50) NOT NULL,    /* Kasutajatüübi lühinimi. */
	description  VARCHAR2(4000),    /* Kasutajatüübi kirjeldus. */
	disk_quota   NUMBER(18)    /* Määrab kasutajatüübi vaikimisi kehtiva mahupiirangu baitides. */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..USERTYPE IS 'Kasutajatüüpide andmed. Kasutajatüüpe on kolm: 
 1. Eraisik (person) 2. Ettevõte (company) 3. Asutus (institution)';
COMMENT ON COLUMN &&ADIT_SCHEMA..USERTYPE.short_name   IS 'Kasutajatüübi lühinimi.';
COMMENT ON COLUMN &&ADIT_SCHEMA..USERTYPE.description  IS 'Kasutajatüübi kirjeldus.';
COMMENT ON COLUMN &&ADIT_SCHEMA..USERTYPE.disk_quota   IS 'Määrab kasutajatüübi vaikimisi kehtiva mahupiirangu baitides.';


CREATE TABLE &&ADIT_SCHEMA..NOTIFICATION
(
	ID                             NUMBER(18) NOT NULL,      /* Teavituse unikaalne identifikaator kohalikus andmebaasis */
	user_code                      VARCHAR2(50),             /* Isiku või asutuse kood, kellele teavitus saadeti */
	document_id                    NUMBER(12) NOT NULL,      /* Teavitusega seotud dokumendi ID */
	event_date                     DATE,                     /* Teavitatava sündmuse toimumise kuupäev ja kellaaeg */
	notification_type              VARCHAR2(50) NOT NULL,    /* Teavituse tüübi lühinimi */
	notification_text              VARCHAR2(4000),           /* Teavituse sisu */
	notification_id                NUMBER(12),               /* Teavituse ID teavituskalendris */
	notification_sending_date      DATE                      /* Teavituse teavituskalendrisse edastamise aeg */
) TABLESPACE &&ADIT_TABLE_TABLESPACE.;

COMMENT ON TABLE &&ADIT_SCHEMA..NOTIFICATION IS 'Teavituskalendri teavitused';
COMMENT ON COLUMN &&ADIT_SCHEMA..NOTIFICATION.ID IS 'Teavituse unikaalne identifikaator kohalikus andmebaasis';
COMMENT ON COLUMN &&ADIT_SCHEMA..NOTIFICATION.user_code IS 'Isiku või asutuse kood, kellele teavitus saadeti';
COMMENT ON COLUMN &&ADIT_SCHEMA..NOTIFICATION.document_id IS 'Teavitusega seotud dokumendi ID';
COMMENT ON COLUMN &&ADIT_SCHEMA..NOTIFICATION.event_date IS 'Teavitatava sündmuse toimumise kuupäev ja kellaaeg';
COMMENT ON COLUMN &&ADIT_SCHEMA..NOTIFICATION.notification_type IS 'Teavituse tüübi lühinimi';
COMMENT ON COLUMN &&ADIT_SCHEMA..NOTIFICATION.notification_text IS 'Teavituse sisu';
COMMENT ON COLUMN &&ADIT_SCHEMA..NOTIFICATION.notification_id IS 'Teavituse ID teavituskalendris';
COMMENT ON COLUMN &&ADIT_SCHEMA..NOTIFICATION.notification_sending_date IS 'Teavituse teavituskalendrisse edastamise aeg';


/* Create Primary Key Constraints */
ALTER TABLE &&ADIT_SCHEMA..ACCESS_RESTRICTION ADD CONSTRAINT PK_ACCESS_RESTRICTIONS 
	PRIMARY KEY (remote_application, user_code) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..ADIT_LOG ADD CONSTRAINT PK_ADIT_LOG 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..ADIT_USER ADD CONSTRAINT PK_USERS 
	PRIMARY KEY (user_code) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT ADD CONSTRAINT PK_DOCUMENTS 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_DVK_STATUS ADD CONSTRAINT PK_DOCUMENT_DVK_STATUSES 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_FILE ADD CONSTRAINT PK_DOCUMENT_FILES 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_HISTORY ADD CONSTRAINT PK_DOCUMENT_HISTORY 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_HISTORY_TYPE ADD CONSTRAINT PK_DOCUMENT_HISTORY_TYPE 
	PRIMARY KEY (short_name) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_SHARING ADD CONSTRAINT PK_DOCUMENT_SHARINGS 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_SHARING_TYPE ADD CONSTRAINT PK_DOCUMENT_SHARING_TYPES 
	PRIMARY KEY (short_name) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_TYPE ADD CONSTRAINT PK_DOCUMENT_TYPES 
	PRIMARY KEY (short_name) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_WF_STATUS ADD CONSTRAINT PK_DOCUMENT_WF_STATUSES 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..DOWNLOAD_REQUEST_LOG ADD CONSTRAINT PK_DOWNLOAD_REQUEST_LOG 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..ERROR_LOG ADD CONSTRAINT PK_ERROR_LOG 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..METADATA_REQUEST_LOG ADD CONSTRAINT PK_METADATA_REQUEST_LOG 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..NOTIFICATION_TYPE ADD CONSTRAINT PK_NOTIFICATION_TYPES 
	PRIMARY KEY (short_name) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..REMOTE_APPLICATION ADD CONSTRAINT PK_REMOTE_APPLICATIONS 
	PRIMARY KEY (short_name) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..REQUEST_LOG ADD CONSTRAINT PK_REQUEST_LOG 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..SIGNATURE ADD CONSTRAINT PK_SIGNATURE 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..USER_NOTIFICATION ADD CONSTRAINT PK_NOTIFICATIONS 
	PRIMARY KEY (user_code, notification_type) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

ALTER TABLE &&ADIT_SCHEMA..USERTYPE ADD CONSTRAINT PK_USERTYPES 
	PRIMARY KEY (short_name) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;
 
 ALTER TABLE &&ADIT_SCHEMA..NOTIFICATION ADD CONSTRAINT PK_NOTIFICATION 
	PRIMARY KEY (ID) 
 USING INDEX TABLESPACE &&ADIT_INDEX_TABLESPACE.;

/* Create Foreign Key Constraints */
ALTER TABLE &&ADIT_SCHEMA..ACCESS_RESTRICTION ADD CONSTRAINT remote_application_short_name 
	FOREIGN KEY (remote_application) REFERENCES &&ADIT_SCHEMA..REMOTE_APPLICATION (short_name);

ALTER TABLE &&ADIT_SCHEMA..ACCESS_RESTRICTION ADD CONSTRAINT user_code 
	FOREIGN KEY (user_code) REFERENCES &&ADIT_SCHEMA..ADIT_USER (user_code);

ALTER TABLE &&ADIT_SCHEMA..ADIT_USER ADD CONSTRAINT usertype_short_name 
	FOREIGN KEY (usertype) REFERENCES &&ADIT_SCHEMA..USERTYPE (short_name);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT ADD CONSTRAINT document_dvk_status_id 
	FOREIGN KEY (document_dvk_status_id) REFERENCES &&ADIT_SCHEMA..DOCUMENT_DVK_STATUS (ID);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT ADD CONSTRAINT document_type_short_name 
	FOREIGN KEY (type) REFERENCES &&ADIT_SCHEMA..DOCUMENT_TYPE (short_name);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT ADD CONSTRAINT document_workflow_status_id 
	FOREIGN KEY (document_wf_status_id) REFERENCES &&ADIT_SCHEMA..DOCUMENT_WF_STATUS (ID);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT ADD CONSTRAINT parent_document_id 
	FOREIGN KEY (parent_id) REFERENCES &&ADIT_SCHEMA..DOCUMENT (ID);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT ADD CONSTRAINT doc_remote_app_short_name 
	FOREIGN KEY (remote_application) REFERENCES &&ADIT_SCHEMA..REMOTE_APPLICATION (short_name);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_FILE ADD CONSTRAINT document_id 
	FOREIGN KEY (document_id) REFERENCES &&ADIT_SCHEMA..DOCUMENT (ID);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_HISTORY ADD CONSTRAINT FK_DOCUMENT_HIST_DOCUMENT_HIST 
	FOREIGN KEY (document_history_type) REFERENCES &&ADIT_SCHEMA..DOCUMENT_HISTORY_TYPE (short_name);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_HISTORY ADD CONSTRAINT FK_DOCUMENT_HIST_REMOTE_APPLIC 
	FOREIGN KEY (remote_application) REFERENCES &&ADIT_SCHEMA..REMOTE_APPLICATION (short_name);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_HISTORY ADD CONSTRAINT FK_DOCUMENT_HISTORY_DOCUMENT 
	FOREIGN KEY (document_id) REFERENCES &&ADIT_SCHEMA..DOCUMENT (ID);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_HISTORY ADD CONSTRAINT history_user_code 
	FOREIGN KEY (user_code) REFERENCES &&ADIT_SCHEMA..ADIT_USER (user_code);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_SHARING ADD CONSTRAINT sharing_document_id 
	FOREIGN KEY (document_id) REFERENCES &&ADIT_SCHEMA..DOCUMENT (ID);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_SHARING ADD CONSTRAINT dvk_status_id 
	FOREIGN KEY (dvk_status_id) REFERENCES &&ADIT_SCHEMA..DOCUMENT_DVK_STATUS (ID);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_SHARING ADD CONSTRAINT sharing_type_short_name 
	FOREIGN KEY (sharing_type) REFERENCES &&ADIT_SCHEMA..DOCUMENT_SHARING_TYPE (short_name);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_SHARING ADD CONSTRAINT sharing_user_code 
	FOREIGN KEY (user_code) REFERENCES &&ADIT_SCHEMA..ADIT_USER (user_code);

ALTER TABLE &&ADIT_SCHEMA..DOCUMENT_SHARING ADD CONSTRAINT wf_status_id 
	FOREIGN KEY (wf_status_id) REFERENCES &&ADIT_SCHEMA..DOCUMENT_WF_STATUS (ID);

ALTER TABLE &&ADIT_SCHEMA..SIGNATURE ADD CONSTRAINT FK_SIGNATURE_DOCUMENT 
	FOREIGN KEY (document_id) REFERENCES &&ADIT_SCHEMA..DOCUMENT (ID);

ALTER TABLE &&ADIT_SCHEMA..SIGNATURE ADD CONSTRAINT FK_SIGNATURE_USER 
	FOREIGN KEY (user_code) REFERENCES &&ADIT_SCHEMA..ADIT_USER (user_code);

ALTER TABLE &&ADIT_SCHEMA..USER_NOTIFICATION ADD CONSTRAINT notification_type_short_name 
	FOREIGN KEY (notification_type) REFERENCES &&ADIT_SCHEMA..NOTIFICATION_TYPE (short_name);

ALTER TABLE &&ADIT_SCHEMA..USER_NOTIFICATION ADD CONSTRAINT notification_user_code 
	FOREIGN KEY (user_code) REFERENCES &&ADIT_SCHEMA..ADIT_USER (user_code);
	
/* Create Triggers */
CREATE SEQUENCE &&ADIT_SCHEMA..ADIT_LOG_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE OR REPLACE TRIGGER &&ADIT_SCHEMA..SET_ADIT_LOG_ID
BEFORE INSERT
ON &&ADIT_SCHEMA..ADIT_LOG
FOR EACH ROW
BEGIN
  SELECT &&ADIT_SCHEMA..ADIT_LOG_ID_SEQ.NEXTVAL
  INTO :NEW.ID
  FROM DUAL;
END;
/

CREATE SEQUENCE &&ADIT_SCHEMA..DOCUMENT_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE &&ADIT_SCHEMA..DOCUMENT_FILE_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE &&ADIT_SCHEMA..DOCUMENT_HISTORY_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE &&ADIT_SCHEMA..DOCUMENT_SHARING_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE &&ADIT_SCHEMA..DOWNLOAD_REQUEST_LOG_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE &&ADIT_SCHEMA..ERROR_LOG_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE &&ADIT_SCHEMA..METADATA_REQUEST_LOG_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE &&ADIT_SCHEMA..REQUEST_LOG_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE &&ADIT_SCHEMA..SIGNATURE_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE &&ADIT_SCHEMA..NOTIFICATION_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

CREATE SEQUENCE &&ADIT_SCHEMA..ACCESS_RESTR_ID_SEQ
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

/* Create indexes */
/* All primary key indexes were created with primary key constraints */
CREATE INDEX &&ADIT_SCHEMA..access_restriction_app_idx ON &&ADIT_SCHEMA..access_restriction (remote_application) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..access_restriction_user_idx ON &&ADIT_SCHEMA..access_restriction (user_code) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..adit_user_active_idx ON &&ADIT_SCHEMA..adit_user (active) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..adit_user_usertype_idx ON &&ADIT_SCHEMA..adit_user (usertype) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_dvkstatus_idx ON &&ADIT_SCHEMA..document (document_dvk_status_id) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_documenttype_idx ON &&ADIT_SCHEMA..document (type) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_wfstatus_idx ON &&ADIT_SCHEMA..document (document_wf_status_id) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_parent_idx ON &&ADIT_SCHEMA..document (parent_id) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_app_idx ON &&ADIT_SCHEMA..document (remote_application) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_file_docid_idx ON &&ADIT_SCHEMA..document_file (document_id) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_history_type_idx ON &&ADIT_SCHEMA..document_history (document_history_type) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_history_app_idx ON &&ADIT_SCHEMA..document_history (remote_application) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_history_docid_idx ON &&ADIT_SCHEMA..document_history (document_id) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_history_user_idx ON &&ADIT_SCHEMA..document_history (user_code) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_sharing_docid_idx ON &&ADIT_SCHEMA..document_sharing (document_id) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_sharing_dvkstatus_idx ON &&ADIT_SCHEMA..document_sharing (dvk_status_id) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_sharing_type_idx ON &&ADIT_SCHEMA..document_sharing (sharing_type) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_sharing_user_idx ON &&ADIT_SCHEMA..document_sharing (user_code) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..document_sharing_wfstatus_idx ON &&ADIT_SCHEMA..document_sharing (wf_status_id) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..signature_docid_idx ON &&ADIT_SCHEMA..signature (document_id) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..signature_user_idx ON &&ADIT_SCHEMA..signature (user_code) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..user_notification_type_idx ON &&ADIT_SCHEMA..user_notification (notification_type) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
CREATE INDEX &&ADIT_SCHEMA..user_notification_user_idx ON &&ADIT_SCHEMA..user_notification (user_code) TABLESPACE &&ADIT_INDEX_TABLESPACE.;
/* End of indexes */

-- ADIT user must have execute rights for dbms_crypto package
grant execute on dbms_crypto to &&ADIT_SCHEMA;

-- Stored procedure for doing file deflation directly in database
create or replace
procedure &&ADIT_SCHEMA..DEFLATE_FILE(
    result_rc out sys_refcursor,
    document_id in number,
    file_id in number,
    mark_deleted in number
)
as
item_count number(10,0) := 0;
begin
    select  count(*)
    into    item_count
    from    document_file
    where   document_file.id = file_id;
    
    if (item_count > 0) then
            select  count(*)
            into    item_count
            from    document_file
            where   document_file.id = DEFLATE_FILE.file_id
                    and document_file.document_id = DEFLATE_FILE.document_id;
            
            if (item_count > 0) then
                select  count(*)
                into    item_count
                from    document_file
                where   document_file.id = DEFLATE_FILE.file_id
                        and nvl(document_file.deleted, 0) = 0;
                
                if (item_count > 0) then
                    -- Calculate MD5 hash
                    update	document_file
                    set		  file_data = dbms_crypto.hash(nvl(file_data, empty_blob()), 2),
                            deleted = (case when DEFLATE_FILE.mark_deleted = 1 then 1 else document_file.deleted end)
                    where   id = DEFLATE_FILE.file_id;
                    
                    open result_rc for
                    select  'ok' as result_code
                    from    dual;
                else
                    open result_rc for
                    select  'already_deleted' as result_code
                    from    dual;
                end if;
            else
                open result_rc for
                select  'file_does_not_belong_to_document' as result_code
                from    dual;
            end if;
    else
        open result_rc for
        select  'file_does_not_exist' as result_code
        from    dual;
    end if;
end;
/
