SET search_path = adit, pg_catalog;
ALTER TABLE ONLY adit.document DROP CONSTRAINT IF EXISTS parent_document_id;
DROP TRIGGER IF EXISTS tr_user_notification_log ON adit.user_notification;
DROP TRIGGER IF EXISTS tr_usertype_log ON adit.usertype;
DROP TRIGGER IF EXISTS tr_signature_log ON adit.signature;
DROP TRIGGER IF EXISTS tr_remote_application_log ON adit.remote_application;
DROP TRIGGER IF EXISTS tr_notification_type_log ON adit.notification_type;
DROP TRIGGER IF EXISTS tr_notification_log ON adit.notification;
DROP TRIGGER IF EXISTS tr_doc_dvk_status_log ON adit.document_dvk_status;
DROP TRIGGER IF EXISTS tr_document_wf_status_log ON adit.document_wf_status;
DROP TRIGGER IF EXISTS tr_document_type_log ON adit.document_type;
DROP TRIGGER IF EXISTS tr_document_sharing_type_log ON adit.document_sharing_type;
DROP TRIGGER IF EXISTS tr_document_sharing_log ON adit.document_sharing;
DROP TRIGGER IF EXISTS tr_document_log ON adit.document;
DROP TRIGGER IF EXISTS tr_document_history_type_log ON adit.document_history_type;
DROP TRIGGER IF EXISTS tr_document_history_log ON adit.document_history;
DROP TRIGGER IF EXISTS tr_document_file_log ON adit.document_file;
DROP TRIGGER IF EXISTS tr_adit_user_log ON adit.adit_user;
DROP TRIGGER IF EXISTS tr_access_restriction_log ON adit.access_restriction;
DROP TRIGGER IF EXISTS set_adit_log_id ON adit.adit_log;
DROP INDEX IF EXISTS adit.access_restriction_app_idx;
DROP INDEX IF EXISTS adit.access_restriction_user_idx;
DROP INDEX IF EXISTS adit.maintenance_job_search_idx;
DROP INDEX IF EXISTS adit.signature_user_idx;
DROP INDEX IF EXISTS adit.signature_docid_idx;
DROP INDEX IF EXISTS adit.user_notification_type_idx;
DROP INDEX IF EXISTS adit.user_notification_user_idx;
DROP INDEX IF EXISTS adit.document_history_user_idx;
DROP INDEX IF EXISTS adit.document_history_app_idx;
DROP INDEX IF EXISTS adit.document_history_docid_idx;
DROP INDEX IF EXISTS adit.document_history_search_idx;
DROP INDEX IF EXISTS adit.document_history_type_idx;
DROP INDEX IF EXISTS adit.document_file_docid_idx;
DROP INDEX IF EXISTS adit.document_parent_idx;
DROP INDEX IF EXISTS adit.document_app_idx;
DROP INDEX IF EXISTS adit.document_documenttype_idx;
DROP INDEX IF EXISTS adit.document_wfstatus_idx;
DROP INDEX IF EXISTS adit.document_dvkstatus_idx;
DROP INDEX IF EXISTS adit.document_sharing_dvkstatus_idx;
DROP INDEX IF EXISTS adit.document_sharing_user_idx;
DROP INDEX IF EXISTS adit.document_sharing_docid_idx;
DROP INDEX IF EXISTS adit.document_sharing_type_idx;
DROP INDEX IF EXISTS adit.document_sharing_wfstatus_idx;
DROP INDEX IF EXISTS adit.adit_user_active_idx;
DROP INDEX IF EXISTS adit.adit_user_usertype_idx;
SET search_path = aditlog, pg_catalog;
DROP FUNCTION IF EXISTS aditlog.get_current_setting (variable_name varchar);
SET search_path = adit, pg_catalog;
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_user_notification_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_usertype_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_signature_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_remote_application_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_notification_type_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_notification_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_doc_dvk_status_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_document_wf_status_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_document_type_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_document_sharing_type_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_document_sharing_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_document_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_document_history_type_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_document_history_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_document_file_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_adit_user_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_tr_access_restriction_log ();
DROP FUNCTION IF EXISTS adit.trigger_fct_set_adit_log_id ();
SET search_path = adit, pg_catalog;
DROP FUNCTION IF EXISTS adit.remove_signed_file_contents (document_id bigint, file_id bigint, ddoc_start_offset bigint, ddoc_end_offset bigint);
DROP FUNCTION IF EXISTS adit.deflate_file (document_id bigint, file_id bigint, mark_deleted bigint, fail_if_signature bigint);
SET search_path = aditlog, pg_catalog;
DROP FUNCTION IF EXISTS aditlog.get_test_date ();
DROP FUNCTION IF EXISTS aditlog.log_user_contact (user_contact_new adit.user_contact, user_contact_old adit.user_contact, operation text);
DROP FUNCTION IF EXISTS aditlog.log_usertype (usertype_new adit.usertype, usertype_old adit.usertype, operation text);
DROP FUNCTION IF EXISTS aditlog.log_user_notification (user_notification_new adit.user_notification, user_notification_old adit.user_notification, operation text);
DROP FUNCTION IF EXISTS aditlog.log_signature (signature_new adit.signature, signature_old adit.signature, operation text);
DROP FUNCTION IF EXISTS aditlog.log_remote_application (remote_application_new adit.remote_application, remote_application_old adit.remote_application, operation text);
DROP FUNCTION IF EXISTS aditlog.log_notification_type (notification_type_new adit.notification_type, notification_type_old adit.notification_type, operation text);
DROP FUNCTION IF EXISTS aditlog.log_document_wf_status (document_wf_status_new adit.document_wf_status, document_wf_status_old adit.document_wf_status, operation text);
DROP FUNCTION IF EXISTS aditlog.log_notification (notification_new adit.notification, notification_old adit.notification, operation text);
DROP FUNCTION IF EXISTS aditlog.log_document_type (document_type_new adit.document_type, document_type_old adit.document_type, operation text);
DROP FUNCTION IF EXISTS aditlog.log_document_sharing_type (document_sharing_type_new adit.document_sharing_type, document_sharing_type_old adit.document_sharing_type, operation text);
SET search_path = adit, pg_catalog;
DROP SEQUENCE IF EXISTS adit.user_contact_id_seq;
DROP SEQUENCE IF EXISTS adit.signature_id_seq;
DROP SEQUENCE IF EXISTS adit.request_log_id_seq;
DROP SEQUENCE IF EXISTS adit.notification_id_seq;
DROP SEQUENCE IF EXISTS adit.metadata_request_log_id_seq;
DROP SEQUENCE IF EXISTS adit.error_log_id_seq;
DROP SEQUENCE IF EXISTS adit.download_request_log_id_seq;
DROP SEQUENCE IF EXISTS adit.document_sharing_id_seq;
DROP SEQUENCE IF EXISTS adit.document_id_seq;
DROP SEQUENCE IF EXISTS adit.document_history_id_seq;
DROP SEQUENCE IF EXISTS adit.document_file_id_seq;
DROP SEQUENCE IF EXISTS adit.adit_log_id_seq;
SET search_path = aditlog, pg_catalog;
DROP FUNCTION IF EXISTS aditlog.log_document_sharing (document_sharing_new adit.document_sharing, document_sharing_old adit.document_sharing, operation text);
DROP FUNCTION IF EXISTS aditlog.log_document_history_type (document_history_type_new adit.document_history_type, document_history_type_old adit.document_history_type, operation text);
DROP FUNCTION IF EXISTS aditlog.log_document_history (document_history_new adit.document_history, document_history_old adit.document_history, operation text);
DROP FUNCTION IF EXISTS aditlog.log_document_dvk_status (document_dvk_status_new adit.document_dvk_status, document_dvk_status_old adit.document_dvk_status, operation text);
DROP FUNCTION IF EXISTS aditlog.log_document (document_new adit.document, document_old adit.document, operation text);
DROP FUNCTION IF EXISTS aditlog.log_document_file (document_file_new adit.document_file, document_file_old adit.document_file, operation text);
DROP FUNCTION IF EXISTS aditlog.log_adit_user (adit_user_new adit.adit_user, adit_user_old adit.adit_user, operation text);
DROP FUNCTION IF EXISTS aditlog.log_access_restriction (access_restriction_new adit.access_restriction, access_restriction_old adit.access_restriction, operation text);
SET search_path = adit, pg_catalog;
DROP FUNCTION IF EXISTS adit.set_job_running_status (job_id bigint, is_running bigint);
DROP TABLE IF EXISTS adit.notification;
DROP TABLE IF EXISTS adit.error_log;
DROP TABLE IF EXISTS adit.access_restriction;
DROP TABLE IF EXISTS adit.maintenance_job;
DROP TABLE IF EXISTS adit.signature;
DROP TABLE IF EXISTS adit.document_file_type;
DROP TABLE IF EXISTS adit.user_notification;
DROP TABLE IF EXISTS adit.metadata_request_log;
DROP TABLE IF EXISTS adit.adit_log;
DROP TABLE IF EXISTS adit.request_log;
DROP TABLE IF EXISTS adit.document_history;
DROP TABLE IF EXISTS adit.document_history_type;
DROP TABLE IF EXISTS adit.notification_type;
DROP TABLE IF EXISTS adit.download_request_log;
DROP TABLE IF EXISTS adit.document_file;
DROP TABLE IF EXISTS adit.document_sharing;
DROP TABLE IF EXISTS adit.document;
DROP TABLE IF EXISTS adit.remote_application;
DROP TABLE IF EXISTS adit.document_type;
DROP TABLE IF EXISTS adit.document_dvk_status;
DROP TABLE IF EXISTS adit.document_sharing_type;
DROP TABLE IF EXISTS adit.document_wf_status;
DROP TABLE IF EXISTS adit.user_contact;
DROP TABLE IF EXISTS adit.adit_user;
DROP TABLE IF EXISTS adit.usertype;
DROP SCHEMA IF EXISTS adit;
DROP SCHEMA IF EXISTS aditlog;
