package ee.adit.dao;

// Generated 11.05.2010 17:19:11 by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * DocumentHistory generated by hbm2java
 */
public class DocumentHistory implements java.io.Serializable {

	private BigDecimal historyEventId;
	private Users users;
	private Documents documents;
	private DocumentHistoryTypes documentHistoryTypes;
	private RemoteApplications remoteApplications;
	private String description;
	private Serializable eventDate;

	public DocumentHistory() {
	}

	public DocumentHistory(BigDecimal historyEventId, Users users,
			Documents documents, DocumentHistoryTypes documentHistoryTypes,
			RemoteApplications remoteApplications, Serializable eventDate) {
		this.historyEventId = historyEventId;
		this.users = users;
		this.documents = documents;
		this.documentHistoryTypes = documentHistoryTypes;
		this.remoteApplications = remoteApplications;
		this.eventDate = eventDate;
	}

	public DocumentHistory(BigDecimal historyEventId, Users users,
			Documents documents, DocumentHistoryTypes documentHistoryTypes,
			RemoteApplications remoteApplications, String description,
			Serializable eventDate) {
		this.historyEventId = historyEventId;
		this.users = users;
		this.documents = documents;
		this.documentHistoryTypes = documentHistoryTypes;
		this.remoteApplications = remoteApplications;
		this.description = description;
		this.eventDate = eventDate;
	}

	public BigDecimal getHistoryEventId() {
		return this.historyEventId;
	}

	public void setHistoryEventId(BigDecimal historyEventId) {
		this.historyEventId = historyEventId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Documents getDocuments() {
		return this.documents;
	}

	public void setDocuments(Documents documents) {
		this.documents = documents;
	}

	public DocumentHistoryTypes getDocumentHistoryTypes() {
		return this.documentHistoryTypes;
	}

	public void setDocumentHistoryTypes(
			DocumentHistoryTypes documentHistoryTypes) {
		this.documentHistoryTypes = documentHistoryTypes;
	}

	public RemoteApplications getRemoteApplications() {
		return this.remoteApplications;
	}

	public void setRemoteApplications(RemoteApplications remoteApplications) {
		this.remoteApplications = remoteApplications;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Serializable getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Serializable eventDate) {
		this.eventDate = eventDate;
	}

}
