package ee.adit.dao;

// Generated 11.05.2010 17:19:11 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentHistoryTypes generated by hbm2java
 */
public class DocumentHistoryTypes implements java.io.Serializable {

	private long documentHistoryTypeId;
	private String description;
	private Set documentHistories = new HashSet(0);

	public DocumentHistoryTypes() {
	}

	public DocumentHistoryTypes(long documentHistoryTypeId) {
		this.documentHistoryTypeId = documentHistoryTypeId;
	}

	public DocumentHistoryTypes(long documentHistoryTypeId, String description,
			Set documentHistories) {
		this.documentHistoryTypeId = documentHistoryTypeId;
		this.description = description;
		this.documentHistories = documentHistories;
	}

	public long getDocumentHistoryTypeId() {
		return this.documentHistoryTypeId;
	}

	public void setDocumentHistoryTypeId(long documentHistoryTypeId) {
		this.documentHistoryTypeId = documentHistoryTypeId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDocumentHistories() {
		return this.documentHistories;
	}

	public void setDocumentHistories(Set documentHistories) {
		this.documentHistories = documentHistories;
	}

}
