package ee.adit.dao;

// Generated 11.05.2010 17:19:11 by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.sql.Blob;

/**
 * DocumentFiles generated by hbm2java
 */
public class DocumentFiles implements java.io.Serializable {

	private BigDecimal documentFileId;
	private Documents documents;
	private String fileName;
	private String contentType;
	private String description;
	private Blob fileData;
	private BigDecimal fileSizeBytes;

	public DocumentFiles() {
	}

	public DocumentFiles(BigDecimal documentFileId, Documents documents) {
		this.documentFileId = documentFileId;
		this.documents = documents;
	}

	public DocumentFiles(BigDecimal documentFileId, Documents documents,
			String fileName, String contentType, String description,
			Blob fileData, BigDecimal fileSizeBytes) {
		this.documentFileId = documentFileId;
		this.documents = documents;
		this.fileName = fileName;
		this.contentType = contentType;
		this.description = description;
		this.fileData = fileData;
		this.fileSizeBytes = fileSizeBytes;
	}

	public BigDecimal getDocumentFileId() {
		return this.documentFileId;
	}

	public void setDocumentFileId(BigDecimal documentFileId) {
		this.documentFileId = documentFileId;
	}

	public Documents getDocuments() {
		return this.documents;
	}

	public void setDocuments(Documents documents) {
		this.documents = documents;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Blob getFileData() {
		return this.fileData;
	}

	public void setFileData(Blob fileData) {
		this.fileData = fileData;
	}

	public BigDecimal getFileSizeBytes() {
		return this.fileSizeBytes;
	}

	public void setFileSizeBytes(BigDecimal fileSizeBytes) {
		this.fileSizeBytes = fileSizeBytes;
	}

}
