package ee.adit.dao;

// Generated 11.05.2010 17:19:11 by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Documents generated by hbm2java
 */
public class Documents implements java.io.Serializable {

	private BigDecimal documentId;
	private Documents documents;
	private DocumentWorkflowStatuses documentWorkflowStatuses;
	private DocumentTypes documentTypes;
	private RemoteApplications remoteApplications;
	private DocumentDvkStatuses documentDvkStatuses;
	private String documentGuid;
	private String title;
	private String creatorCode;
	private Date creationDate;
	private Date lastModifiedDate;
	private BigDecimal dvkId;
	private Date lastAccessDate;
	private boolean isLocked;
	private Date lockingDate;
	private boolean isSignable;
	private boolean isArchived;
	private Date archivingDate;
	private Set documentSharingses = new HashSet(0);
	private Set documentFileses = new HashSet(0);
	private Set documentses = new HashSet(0);
	private Set documentHistories = new HashSet(0);

	public Documents() {
	}

	public Documents(BigDecimal documentId,
			DocumentWorkflowStatuses documentWorkflowStatuses,
			RemoteApplications remoteApplications,
			DocumentDvkStatuses documentDvkStatuses, boolean isLocked,
			boolean isSignable, boolean isArchived) {
		this.documentId = documentId;
		this.documentWorkflowStatuses = documentWorkflowStatuses;
		this.remoteApplications = remoteApplications;
		this.documentDvkStatuses = documentDvkStatuses;
		this.isLocked = isLocked;
		this.isSignable = isSignable;
		this.isArchived = isArchived;
	}

	public Documents(BigDecimal documentId, Documents documents,
			DocumentWorkflowStatuses documentWorkflowStatuses,
			DocumentTypes documentTypes, RemoteApplications remoteApplications,
			DocumentDvkStatuses documentDvkStatuses, String documentGuid,
			String title, String creatorCode, Date creationDate,
			Date lastModifiedDate, BigDecimal dvkId, Date lastAccessDate,
			boolean isLocked, Date lockingDate, boolean isSignable,
			boolean isArchived, Date archivingDate, Set documentSharingses,
			Set documentFileses, Set documentses, Set documentHistories) {
		this.documentId = documentId;
		this.documents = documents;
		this.documentWorkflowStatuses = documentWorkflowStatuses;
		this.documentTypes = documentTypes;
		this.remoteApplications = remoteApplications;
		this.documentDvkStatuses = documentDvkStatuses;
		this.documentGuid = documentGuid;
		this.title = title;
		this.creatorCode = creatorCode;
		this.creationDate = creationDate;
		this.lastModifiedDate = lastModifiedDate;
		this.dvkId = dvkId;
		this.lastAccessDate = lastAccessDate;
		this.isLocked = isLocked;
		this.lockingDate = lockingDate;
		this.isSignable = isSignable;
		this.isArchived = isArchived;
		this.archivingDate = archivingDate;
		this.documentSharingses = documentSharingses;
		this.documentFileses = documentFileses;
		this.documentses = documentses;
		this.documentHistories = documentHistories;
	}

	public BigDecimal getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(BigDecimal documentId) {
		this.documentId = documentId;
	}

	public Documents getDocuments() {
		return this.documents;
	}

	public void setDocuments(Documents documents) {
		this.documents = documents;
	}

	public DocumentWorkflowStatuses getDocumentWorkflowStatuses() {
		return this.documentWorkflowStatuses;
	}

	public void setDocumentWorkflowStatuses(
			DocumentWorkflowStatuses documentWorkflowStatuses) {
		this.documentWorkflowStatuses = documentWorkflowStatuses;
	}

	public DocumentTypes getDocumentTypes() {
		return this.documentTypes;
	}

	public void setDocumentTypes(DocumentTypes documentTypes) {
		this.documentTypes = documentTypes;
	}

	public RemoteApplications getRemoteApplications() {
		return this.remoteApplications;
	}

	public void setRemoteApplications(RemoteApplications remoteApplications) {
		this.remoteApplications = remoteApplications;
	}

	public DocumentDvkStatuses getDocumentDvkStatuses() {
		return this.documentDvkStatuses;
	}

	public void setDocumentDvkStatuses(DocumentDvkStatuses documentDvkStatuses) {
		this.documentDvkStatuses = documentDvkStatuses;
	}

	public String getDocumentGuid() {
		return this.documentGuid;
	}

	public void setDocumentGuid(String documentGuid) {
		this.documentGuid = documentGuid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCreatorCode() {
		return this.creatorCode;
	}

	public void setCreatorCode(String creatorCode) {
		this.creatorCode = creatorCode;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public BigDecimal getDvkId() {
		return this.dvkId;
	}

	public void setDvkId(BigDecimal dvkId) {
		this.dvkId = dvkId;
	}

	public Date getLastAccessDate() {
		return this.lastAccessDate;
	}

	public void setLastAccessDate(Date lastAccessDate) {
		this.lastAccessDate = lastAccessDate;
	}

	public boolean isIsLocked() {
		return this.isLocked;
	}

	public void setIsLocked(boolean isLocked) {
		this.isLocked = isLocked;
	}

	public Date getLockingDate() {
		return this.lockingDate;
	}

	public void setLockingDate(Date lockingDate) {
		this.lockingDate = lockingDate;
	}

	public boolean isIsSignable() {
		return this.isSignable;
	}

	public void setIsSignable(boolean isSignable) {
		this.isSignable = isSignable;
	}

	public boolean isIsArchived() {
		return this.isArchived;
	}

	public void setIsArchived(boolean isArchived) {
		this.isArchived = isArchived;
	}

	public Date getArchivingDate() {
		return this.archivingDate;
	}

	public void setArchivingDate(Date archivingDate) {
		this.archivingDate = archivingDate;
	}

	public Set getDocumentSharingses() {
		return this.documentSharingses;
	}

	public void setDocumentSharingses(Set documentSharingses) {
		this.documentSharingses = documentSharingses;
	}

	public Set getDocumentFileses() {
		return this.documentFileses;
	}

	public void setDocumentFileses(Set documentFileses) {
		this.documentFileses = documentFileses;
	}

	public Set getDocumentses() {
		return this.documentses;
	}

	public void setDocumentses(Set documentses) {
		this.documentses = documentses;
	}

	public Set getDocumentHistories() {
		return this.documentHistories;
	}

	public void setDocumentHistories(Set documentHistories) {
		this.documentHistories = documentHistories;
	}

}
