package ee.adit.dao;

// Generated 11.05.2010 17:19:11 by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * DocumentSharings generated by hbm2java
 */
public class DocumentSharings implements java.io.Serializable {

	private BigDecimal documentSharingId;
	private DocumentWorkflowStatuses documentWorkflowStatuses;
	private Users users;
	private DocumentSharingTypes documentSharingTypes;
	private Documents documents;
	private DocumentDvkStatuses documentDvkStatuses;
	private String taskDescription;
	private Date creationDate;
	private BigDecimal documentDvkId;
	private Date lastAccessDate;

	public DocumentSharings() {
	}

	public DocumentSharings(BigDecimal documentSharingId,
			DocumentWorkflowStatuses documentWorkflowStatuses, Users users,
			DocumentSharingTypes documentSharingTypes, Documents documents,
			DocumentDvkStatuses documentDvkStatuses) {
		this.documentSharingId = documentSharingId;
		this.documentWorkflowStatuses = documentWorkflowStatuses;
		this.users = users;
		this.documentSharingTypes = documentSharingTypes;
		this.documents = documents;
		this.documentDvkStatuses = documentDvkStatuses;
	}

	public DocumentSharings(BigDecimal documentSharingId,
			DocumentWorkflowStatuses documentWorkflowStatuses, Users users,
			DocumentSharingTypes documentSharingTypes, Documents documents,
			DocumentDvkStatuses documentDvkStatuses, String taskDescription,
			Date creationDate, BigDecimal documentDvkId, Date lastAccessDate) {
		this.documentSharingId = documentSharingId;
		this.documentWorkflowStatuses = documentWorkflowStatuses;
		this.users = users;
		this.documentSharingTypes = documentSharingTypes;
		this.documents = documents;
		this.documentDvkStatuses = documentDvkStatuses;
		this.taskDescription = taskDescription;
		this.creationDate = creationDate;
		this.documentDvkId = documentDvkId;
		this.lastAccessDate = lastAccessDate;
	}

	public BigDecimal getDocumentSharingId() {
		return this.documentSharingId;
	}

	public void setDocumentSharingId(BigDecimal documentSharingId) {
		this.documentSharingId = documentSharingId;
	}

	public DocumentWorkflowStatuses getDocumentWorkflowStatuses() {
		return this.documentWorkflowStatuses;
	}

	public void setDocumentWorkflowStatuses(
			DocumentWorkflowStatuses documentWorkflowStatuses) {
		this.documentWorkflowStatuses = documentWorkflowStatuses;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public DocumentSharingTypes getDocumentSharingTypes() {
		return this.documentSharingTypes;
	}

	public void setDocumentSharingTypes(
			DocumentSharingTypes documentSharingTypes) {
		this.documentSharingTypes = documentSharingTypes;
	}

	public Documents getDocuments() {
		return this.documents;
	}

	public void setDocuments(Documents documents) {
		this.documents = documents;
	}

	public DocumentDvkStatuses getDocumentDvkStatuses() {
		return this.documentDvkStatuses;
	}

	public void setDocumentDvkStatuses(DocumentDvkStatuses documentDvkStatuses) {
		this.documentDvkStatuses = documentDvkStatuses;
	}

	public String getTaskDescription() {
		return this.taskDescription;
	}

	public void setTaskDescription(String taskDescription) {
		this.taskDescription = taskDescription;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public BigDecimal getDocumentDvkId() {
		return this.documentDvkId;
	}

	public void setDocumentDvkId(BigDecimal documentDvkId) {
		this.documentDvkId = documentDvkId;
	}

	public Date getLastAccessDate() {
		return this.lastAccessDate;
	}

	public void setLastAccessDate(Date lastAccessDate) {
		this.lastAccessDate = lastAccessDate;
	}

}
