package ee.adit.dao;

// Generated 11.05.2010 17:19:11 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Usertypes generated by hbm2java
 */
public class Usertypes implements java.io.Serializable {

	private String usertypeShortName;
	private String description;
	private Set userses = new HashSet(0);

	public Usertypes() {
	}

	public Usertypes(String usertypeShortName) {
		this.usertypeShortName = usertypeShortName;
	}

	public Usertypes(String usertypeShortName, String description, Set userses) {
		this.usertypeShortName = usertypeShortName;
		this.description = description;
		this.userses = userses;
	}

	public String getUsertypeShortName() {
		return this.usertypeShortName;
	}

	public void setUsertypeShortName(String usertypeShortName) {
		this.usertypeShortName = usertypeShortName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
