package ee.adit.dao;

// Generated 11.05.2010 17:19:11 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String userCode;
	private Usertypes usertypes;
	private String fullName;
	private boolean isActive;
	private Set documentHistories = new HashSet(0);
	private Set documentSharingses = new HashSet(0);
	private Set accessRestrictionses = new HashSet(0);
	private Set notificationTypeses = new HashSet(0);

	public Users() {
	}

	public Users(String userCode, Usertypes usertypes, String fullName,
			boolean isActive) {
		this.userCode = userCode;
		this.usertypes = usertypes;
		this.fullName = fullName;
		this.isActive = isActive;
	}

	public Users(String userCode, Usertypes usertypes, String fullName,
			boolean isActive, Set documentHistories, Set documentSharingses,
			Set accessRestrictionses, Set notificationTypeses) {
		this.userCode = userCode;
		this.usertypes = usertypes;
		this.fullName = fullName;
		this.isActive = isActive;
		this.documentHistories = documentHistories;
		this.documentSharingses = documentSharingses;
		this.accessRestrictionses = accessRestrictionses;
		this.notificationTypeses = notificationTypeses;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public Usertypes getUsertypes() {
		return this.usertypes;
	}

	public void setUsertypes(Usertypes usertypes) {
		this.usertypes = usertypes;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set getDocumentHistories() {
		return this.documentHistories;
	}

	public void setDocumentHistories(Set documentHistories) {
		this.documentHistories = documentHistories;
	}

	public Set getDocumentSharingses() {
		return this.documentSharingses;
	}

	public void setDocumentSharingses(Set documentSharingses) {
		this.documentSharingses = documentSharingses;
	}

	public Set getAccessRestrictionses() {
		return this.accessRestrictionses;
	}

	public void setAccessRestrictionses(Set accessRestrictionses) {
		this.accessRestrictionses = accessRestrictionses;
	}

	public Set getNotificationTypeses() {
		return this.notificationTypeses;
	}

	public void setNotificationTypeses(Set notificationTypeses) {
		this.notificationTypeses = notificationTypeses;
	}

}
