CREATE OR REPLACE TRIGGER TR_ACCESS_RESTRICTION_LOG
  after insert or update or delete
  on ACCESS_RESTRICTION referencing old as old new as new
  for each row
DECLARE
  operation varchar2(100);
  ACCESS_RESTRICTION_new ACCESS_RESTRICTION%ROWTYPE;
  ACCESS_RESTRICTION_old ACCESS_RESTRICTION%ROWTYPE;
BEGIN

  if inserting then
    operation := 'INSERT';
  else
    if updating then
      operation := 'UPDATE';
    else
      operation := 'DELETE';
    end if;
  end if;

  ACCESS_RESTRICTION_new.ID := :new.ID;
  ACCESS_RESTRICTION_new.REMOTE_APPLICATION := :new.REMOTE_APPLICATION;
  ACCESS_RESTRICTION_new.USER_CODE := :new.USER_CODE;
  ACCESS_RESTRICTION_new.RESTRICTION := :new.RESTRICTION;
  
  ACCESS_RESTRICTION_old.ID := :old.ID;
  ACCESS_RESTRICTION_old.REMOTE_APPLICATION := :old.REMOTE_APPLICATION;
  ACCESS_RESTRICTION_old.USER_CODE := :old.USER_CODE;
  ACCESS_RESTRICTION_old.RESTRICTION := :old.RESTRICTION;

  ADITLOG.LOG_ACCESS_RESTRICTION(
    ACCESS_RESTRICTION_new,
    ACCESS_RESTRICTION_old,
    operation
  );

END;
/

CREATE OR REPLACE TRIGGER TR_ADIT_USER_LOG
  after insert or update or delete
  on ADIT_USER referencing old as old new as new
  for each row
DECLARE
  operation varchar2(100);
  ADIT_USER_new ADIT_USER%ROWTYPE;
  ADIT_USER_old ADIT_USER%ROWTYPE;
BEGIN

  if inserting then
    operation := 'INSERT';
  else
    if updating then
      operation := 'UPDATE';
    else
      operation := 'DELETE';
    end if;
  end if;
  
  ADIT_USER_new.USER_CODE := :new.USER_CODE;
  ADIT_USER_new.FULL_NAME := :new.FULL_NAME;
  ADIT_USER_new.USERTYPE := :new.USERTYPE;
  ADIT_USER_new.ACTIVE := :new.ACTIVE;
  ADIT_USER_new.DVK_ORG_CODE := :new.DVK_ORG_CODE;
  ADIT_USER_new.DVK_SUBDIVISION_SHORT_NAME := :new.DVK_SUBDIVISION_SHORT_NAME;
  ADIT_USER_new.DVK_OCCUPATION_SHORT_NAME := :new.DVK_OCCUPATION_SHORT_NAME;
  ADIT_USER_new.DISK_QUOTA := :new.DISK_QUOTA;
  ADIT_USER_new.DEACTIVATION_DATE := :new.DEACTIVATION_DATE;
  
  ADIT_USER_old.USER_CODE := :old.USER_CODE;
  ADIT_USER_old.FULL_NAME := :old.FULL_NAME;
  ADIT_USER_old.USERTYPE := :old.USERTYPE;
  ADIT_USER_old.ACTIVE := :old.ACTIVE;
  ADIT_USER_old.DVK_ORG_CODE := :old.DVK_ORG_CODE;
  ADIT_USER_old.DVK_SUBDIVISION_SHORT_NAME := :old.DVK_SUBDIVISION_SHORT_NAME;
  ADIT_USER_old.DVK_OCCUPATION_SHORT_NAME := :old.DVK_OCCUPATION_SHORT_NAME;
  ADIT_USER_old.DISK_QUOTA := :old.DISK_QUOTA;
  ADIT_USER_old.DEACTIVATION_DATE := :old.DEACTIVATION_DATE;

  ADITLOG.LOG_ADIT_USER(
    ADIT_USER_new,
    ADIT_USER_old,
    operation
  );

END;
/

CREATE OR REPLACE TRIGGER TR_DOCUMENT_LOG
  after insert or update or delete
  on DOCUMENT referencing old as old new as new
  for each row
DECLARE
  operation varchar2(100);
  DOCUMENT_new DOCUMENT%ROWTYPE;
  DOCUMENT_old DOCUMENT%ROWTYPE;
BEGIN

  if inserting then
    operation := 'INSERT';
  else
    if updating then
      operation := 'UPDATE';
    else
      operation := 'DELETE';
    end if;
  end if;

  DOCUMENT_new.ID := :new.ID;
  DOCUMENT_new.GUID := :new.GUID;
  DOCUMENT_new.TITLE := :new.TITLE;
  DOCUMENT_new.TYPE := :new.TYPE;
  DOCUMENT_new.CREATOR_CODE := :new.CREATOR_CODE;
  DOCUMENT_new.CREATOR_NAME := :new.CREATOR_NAME;
  DOCUMENT_new.CREATOR_USER_CODE := :new.CREATOR_USER_CODE;
  DOCUMENT_new.CREATOR_USER_NAME := :new.CREATOR_USER_NAME;
  DOCUMENT_new.CREATION_DATE := :new.CREATION_DATE;
  DOCUMENT_new.REMOTE_APPLICATION := :new.REMOTE_APPLICATION;
  DOCUMENT_new.LAST_MODIFIED_DATE := :new.LAST_MODIFIED_DATE;
  DOCUMENT_new.DOCUMENT_DVK_STATUS_ID := :new.DOCUMENT_DVK_STATUS_ID;
  DOCUMENT_new.DVK_ID := :new.DVK_ID;
  DOCUMENT_new.DOCUMENT_WF_STATUS_ID := :new.DOCUMENT_WF_STATUS_ID;
  DOCUMENT_new.PARENT_ID := :new.PARENT_ID;
  DOCUMENT_new.LOCKED := :new.LOCKED;
  DOCUMENT_new.LOCKING_DATE := :new.LOCKING_DATE;
  DOCUMENT_new.SIGNABLE := :new.SIGNABLE;
  DOCUMENT_new.DEFLATED := :new.DEFLATED;
  DOCUMENT_new.DEFLATE_DATE := :new.DEFLATE_DATE;
  DOCUMENT_new.DELETED := :new.DELETED;
  
  DOCUMENT_old.ID := :old.ID;
  DOCUMENT_old.GUID := :old.GUID;
  DOCUMENT_old.TITLE := :old.TITLE;
  DOCUMENT_old.TYPE := :old.TYPE;
  DOCUMENT_old.CREATOR_CODE := :old.CREATOR_CODE;
  DOCUMENT_old.CREATOR_NAME := :old.CREATOR_NAME;
  DOCUMENT_old.CREATOR_USER_CODE := :old.CREATOR_USER_CODE;
  DOCUMENT_old.CREATOR_USER_NAME := :old.CREATOR_USER_NAME;
  DOCUMENT_old.CREATION_DATE := :old.CREATION_DATE;
  DOCUMENT_old.REMOTE_APPLICATION := :old.REMOTE_APPLICATION;
  DOCUMENT_old.LAST_MODIFIED_DATE := :old.LAST_MODIFIED_DATE;
  DOCUMENT_old.DOCUMENT_DVK_STATUS_ID := :old.DOCUMENT_DVK_STATUS_ID;
  DOCUMENT_old.DVK_ID := :old.DVK_ID;
  DOCUMENT_old.DOCUMENT_WF_STATUS_ID := :old.DOCUMENT_WF_STATUS_ID;
  DOCUMENT_old.PARENT_ID := :old.PARENT_ID;
  DOCUMENT_old.LOCKED := :old.LOCKED;
  DOCUMENT_old.LOCKING_DATE := :old.LOCKING_DATE;
  DOCUMENT_old.SIGNABLE := :old.SIGNABLE;
  DOCUMENT_old.DEFLATED := :old.DEFLATED;
  DOCUMENT_old.DEFLATE_DATE := :old.DEFLATE_DATE;
  DOCUMENT_old.DELETED := :old.DELETED;

  ADITLOG.LOG_DOCUMENT(
    DOCUMENT_new,
    DOCUMENT_old,
    operation
  );

END;
/


