//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.02 at 02:29:36 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.riik.ee/adit/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ee.adit.pojo;
